store/Cargo.toml
store/src/cli/cli.rs
store/src/config.rs
store/src/db.rs
store/src/main.rs
store/src/migrations.rs
store/src/server/api.rs
store/src/types.rs
utils/Cargo.toml

A few important notes:
- Error handling:
- The code is using `anyhow` as the top-level error. This is because the error messages produced by that library are more informative than the default `main() -> std::Result<>`
- However, `anyhow` requires the wrapped errors to implement `std::error::Error`. Which is an issue in our code and third party libraries
- Also, `anyhow` requires the `Sync` and `Send` marker traits, which was an issue with `deadpool`
- To circumvent the above for the time being, errors are translated using the `anyhow!` macro. In addition to that, I think we should implement `std::error::Error` on all of our error types.
- This PR introduces an async trait to abstract interactions with the underlying database. This is because eventually we may want to move away form sqlite …

store: add sqlite pool and initial migration for nullifier table

---

store/Cargo.toml

As the PR title says, the name should have been `miden-node-store` and not `miden-store` to match the packages name.

store: fix binary name

---

Cargo.toml
proto/Cargo.toml
proto/proto/block_header.proto
proto/proto/rpc.proto
proto/proto/store.proto
proto/src/generated/block_header.rs
proto/src/generated/mod.rs
proto/src/generated/rpc.rs
proto/src/generated/store.rs
proto/src/lib.rs
rpc/Cargo.toml
rpc/src/server/api.rs
store/Cargo.toml
store/src/db.rs
store/src/migrations.rs
store/src/server/api.rs

issue: #20
Adds protobuf message to retrieve a block header by number.
Assumptions:
- A user learns about a block's hash by fetching the block header. So it doesn't make sense to have a fetch block header by block hash.
- A user is not really interested in the changes in the block header, but in the state represented by it. So it doesn't make sense to support fetch for a range of block numbers.
- Instead we should have endpoints that return the historical for on-chain accounts' storage items. This will perform better since it scales by the number of changes to the smart contract, and not by the number of blocks.
- A user doesn't want to download the complete state that is commited to by a block. So it doesn't make sense to reply with data beyond the block header
- Instead we should have …

store: fetch block header by number endpoint

---

proto/proto/requests.proto
proto/proto/responses.proto
proto/proto/store.proto
proto/src/generated/requests.rs
proto/src/generated/responses.rs
proto/src/generated/rpc.rs
proto/src/generated/store.rs
store/src/db/mod.rs
store/src/db/sql.rs
store/src/db/tests.rs
store/src/errors.rs
store/src/main.rs
store/src/server/api.rs
store/src/state.rs

fixes #19 
Notes:
- As with the other endpoints, the message here does not include values that can be computed locally. Namely the nullifiers/account/mmr roots. this is inline with the requests from @bobbinth on previous requests, and the suggestion from @plafer to remove unnecessary validation for the internal system.
- Because the data structures do not support multiple versions, they must be copied before applying the changes. I have created issues on crypto to discuss this.

store: apply_block endpoint

---

proto/proto/requests.proto
proto/src/generated/requests.rs
store/src/state.rs

Instead of requiring block producer to create a merkle tree to obtain the merkle paths, this uses the locally computed tree to retrieve the authentication path. Simplifying the block producer code and reducing the created note message size.

store: reduce note message size

---

block-producer/src/batch_builder/mod.rs
block-producer/src/block.rs
block-producer/src/block_builder/mod.rs
block-producer/src/test_utils/block.rs

Fixes the inconsistency with what the store expects

Block: `created_notes` is now `NoteEnvelope`

---

proto/proto/note.proto
proto/proto/requests.proto
proto/proto/responses.proto
proto/src/conversion.rs
proto/src/generated/note.rs
proto/src/generated/requests.rs
proto/src/generated/responses.rs
store/src/db/mod.rs
store/src/state.rs

This small PR just moves all note-related messages into `note.proto` file. Other changes:
- Left a few TODOs for the future.
- Re-ordered some fields to ensure consistent ordering.
- Changed data type of `sender` to `fixed64` (in the future should be changed to `AccountId`).

Consolidate note messages

---

block-producer/src/batch_builder/mod.rs
block-producer/src/server/api.rs
block-producer/src/state_view/mod.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/state_view/tests/mod.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/test_utils/proven_tx.rs
block-producer/src/test_utils/store.rs
block-producer/src/txqueue/mod.rs
proto/src/conversion.rs

This PR updates the code to match the changes of https://github.com/0xPolygonMiden/miden-base/pull/360/

deps: update code to compile with latest miden-object

---

block-producer/src/server/api.rs
proto/proto/requests.proto
proto/proto/responses.proto
proto/src/generated/requests.rs
proto/src/generated/responses.rs
store/src/server/api.rs
store/src/state.rs

Closes #103
As the PR title says.

proto: get transaction input accepts only one account, fixes #103

---

block-producer/Cargo.toml
block-producer/src/config.rs
block-producer/src/main.rs
block-producer/src/server/api.rs
node/Cargo.toml
node/src/config.rs
node/src/main.rs
rpc/Cargo.toml
rpc/src/config.rs
rpc/src/main.rs
rpc/src/server/api.rs
store/Cargo.toml
store/src/config.rs
store/src/main.rs
store/src/server/api.rs
utils/src/config.rs

- This renamed the `Endpoint` structs, to make it clear they are not reusable
- Added a endpoint method to render the corresponding `Endpoint` url. (an URL is needed because of the protocol)
- Added a top-level config for each server. This gives a namespace for the individual serve types, allowing them to be in the same file. - Configs are under `store`, `block_producer`, and `rpc` namespaces.
- Added tests for the above.
- Now ENV variables are separated by `__` instead of a `_`. This allow configuration names with `_` to be set via environment variables.
fixes #100

config: node with a single config file

---

utils/src/logging.rs

Changes the logging output from:
```
2023-12-20T19:51:01.287915Z  INFO tokio-runtime-worker serve: miden_node_store::server::api: store/src/server/api.rs:38: {"COMPONENT":"miden-store","host":"localhost","message":"Server initialized","port":28943} {}
```
to
```
2023-12-20T19:52:25.752035Z  INFO rpc/src/server/api.rs:97: Server initialized, host: "localhost", port: 57291, COMPONENT: "miden-rpc"
```
Specifically:
- "pretty" output chosen over "json"; I find it much easier to read
- Remove the thread information: it is always `tokio-runtime-worker` anyways so doesn't add valuable information
- `target: false`: This removes the module in which the log occurred, as we already have the exact file & line number where the log occurred (from which I can infer the module if I need to, but …

Fix logging output

---

block-producer/src/main.rs
block-producer/src/server/api.rs
block-producer/src/server/mod.rs
block-producer/src/store/errors.rs
block-producer/src/store/mod.rs
node/src/commands.rs

This PR mostly moves code around (there should be no actual code changes). Specifically, moves `DefaultStore` into `store` module and server start up one module.

Move `DefaultStore` in block producer into `store` module

---

block-producer/src/block_builder/mod.rs
block-producer/src/block_builder/tests.rs
block-producer/src/server/mod.rs

As keenly noticed by @bobbinth, the `block-producer` wasn't wired correctly: `apply_block()` must be called on `StateView`, not the `Store` directly. This PR fixes that.
Initially I thought having only one trait for applying a block (`ApplyBlock`), which both `StateView` and `Store` implement, would be elegant. However, this prevents the type system from telling us when we wired things incorrectly (as we did now). We should potentially revisit this decision and split `ApplyBlock` in 2 traits.

block-producer: apply_block on state_view

---

block-producer/src/batch_builder/batch.rs
block-producer/src/batch_builder/mod.rs
block-producer/src/server/mod.rs

This PR moves `TransactionBatch` into a separate module. There should be no real code changes here.

Move `TransactionBatch` into separate module

---

store/src/state.rs

When addressing #114, we forgot to apply the fix to `State::sync_state` as well. Although I suspect the current code probably didn't work before addressing #114, since I would ultimately expect [this check](https://github.com/0xPolygonMiden/crypto/blob/862ccf54dd24a80b74f1c63baab19ecd34e4f15b/src/merkle/mmr/mod.rs#L37) to fail?
There is still a bug with state sync though (#130)

Fix `forest` parameter in `sync_state`

---

proto/src/conversion.rs
store/src/db/sql.rs
store/src/errors.rs
store/src/state.rs

This PR should fix #133. There were a couple of bugs in the store in the `apply_block` and `get_block_inputs` endpoints. All these are basically "off-by-one" errors in regards to how we handle block numbering. Specifically:
- `get_block_inputs` returned the current state of chain MMR rather than the state as of one block ago. We need the state as of one block ago because we want to send a consistent tuple `(current_block, chain_peaks)` but if we send the latest peaks, that would already include `current_block` in them.
- in `apply_block` we were adding the pervious block header to the chain MMR rather than the new block header.
Also, did some minor refactoring of errors.

Fix chain MMR updates in the store

---

README.md
block-producer/README.md
proto/proto/requests.proto
proto/proto/responses.proto
proto/src/generated/requests.rs
proto/src/generated/responses.rs
rpc/README.md
store/README.md

Hi there,
I've improved README by adding prerequisites, making separated page for each component and API documentation.

Separated docs by components, added API docs

---

block-producer/src/cli/mod.rs
rpc/src/cli/mod.rs
store/src/cli/mod.rs

In this PR I propose a removal of additional cli parameters from block-producer, store and RPC.
They were not in use for now and we were launching the node using config files, hence not needing them for now. 
In the future we will think about how we want to handle the launch of the node.
closes: #124

Removed additional cli parameters from block-producer, store and RPC.

---

block-producer/src/block_builder/mod.rs
block-producer/src/state_view/mod.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/store/mod.rs
block-producer/src/test_utils/store.rs

In this PR I propose to remove `Arc<>` on `Block` for `ApplyBlock`, the Arc<> not being used creates overhead and forces us to use `.clone()` often. Incurring a performance hit.
closes: #99

removed `Arc<>` on `Block` for `ApplyBlock`

---

store/src/db/sql.rs
store/src/migrations.rs
store/src/state.rs

This PR extracts store-related fixes from #155 which close #152 and also make sure `apply_block` request succeeds on the store.

Assorted store fixes

---

.gitignore

As per the PR title. The XDG placement of the DB was removed, meaning the files are now generated where the binary is executed, and this can be inside the git repo. This adds the sqlite files to the gitignore

git: ignore test db files

---

store/src/db/sql.rs

It looks like I only added the `sender` tag filter to the subquery.

bugfix: sender needs to be considered too

---

Cargo.toml
block-producer/Cargo.toml
block-producer/src/block_builder/prover/tests.rs
block-producer/src/test_utils/proven_tx.rs
proto/proto/note.proto
proto/src/conversion.rs
proto/src/generated/note.rs
store/src/db/migrations.rs
store/src/db/sql.rs
store/src/db/tests.rs
store/src/state.rs

Removed `num_assets` from `NoteMetadata` in the miden-node, this will enable the clean update of from the breaking changes made in the miden-base.
Linked to: https://github.com/0xPolygonMiden/miden-base/pull/414
Closes: #169

Removed `num_assets` from NoteMetadata

---

store/src/db/sql.rs

As per the title. This adds order by to the select statements.
fixes #175

db: add order by clauses

---

.editorconfig
proto/proto/account.proto
proto/proto/requests.proto
proto/proto/responses.proto
proto/proto/tsmt.proto
proto/src/generated/account.rs
proto/src/generated/requests.rs
proto/src/generated/responses.rs
proto/src/generated/tsmt.rs
rpc/README.md
store/README.md
store/src/server/api.rs
store/src/state.rs

as per the title, this removes `block_path` and fixes #164

sync_state: remove block_path, fixes #164

---

block-producer/src/txqueue/mod.rs

A small bit of docs for the `TransactionVerifier` trait.

block_producer: Add docs for TransactionVerifier

---

block-producer/src/batch_builder/mod.rs

As per the PR title.
I made an assumption of the design goal while writing the docs, namely that the trait is abstracting over a batch proving strategy, and it can represent a pool of distributed machines instead of an unique machine.

block_producer: add docs for BatchBuilder trait

---

block-producer/src/server/api.rs
block-producer/src/server/mod.rs
block-producer/src/txqueue/mod.rs
block-producer/src/txqueue/tests/mod.rs

1. This trait is currently not used for testing.
2. As it currently stands, the block producer itself is the queue. Meaning I think it is unlikely this queue will need an additional implementation to support a remote queue.
3. This change makes `BlockProducerApi` depend on a concrete struct, making it easier to follow the code, e.g.:
- jump to definition goes to the implementation instead of the trait definition
- the mental model is more direct, removing one indirection level

proposal:  remove transaction queue trait

---

block-producer/src/batch_builder/batch.rs
block-producer/src/batch_builder/mod.rs
block-producer/src/server/mod.rs
block-producer/src/txqueue/mod.rs
rpc/src/server/mod.rs
store/src/db/mod.rs
store/src/server/mod.rs
utils/src/logging.rs

Added logs for transaction batch building flow.
Sample output:
```
2024-01-29T09:01:42.062953Z  INFO block_producer:try_build_batches: miden-block-producer: block-producer/src/txqueue/mod.rs:162: new
2024-01-29T09:01:42.063159Z  INFO block_producer:try_build_batches:batch_builder: miden-block-producer: block-producer/src/txqueue/mod.rs:192: new
2024-01-29T09:01:42.063304Z  INFO block_producer:try_build_batches:batch_builder:build_batch: miden-block-producer: block-producer/src/batch_builder/mod.rs:116: new
2024-01-29T09:01:42.063354Z  INFO block_producer:try_build_batches:batch_builder:build_batch: miden-block-producer: block-producer/src/batch_builder/mod.rs:123: Building a transaction batch, num_txs: 1
2024-01-29T09:01:42.063412Z  INFO …
```

(Logs) Build transactions batch

---

block-producer/src/batch_builder/batch.rs
block-producer/src/batch_builder/errors.rs
block-producer/src/batch_builder/mod.rs
block-producer/src/batch_builder/tests/mod.rs
block-producer/src/block_builder/mod.rs
block-producer/src/block_builder/prover/block_witness.rs
block-producer/src/block_builder/prover/tests.rs
block-producer/src/block_builder/tests.rs
block-producer/src/lib.rs
block-producer/src/server/api.rs
block-producer/src/state_view/mod.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/state_view/tests/mod.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/store/mod.rs
block-producer/src/test_utils/batch.rs
block-producer/src/test_utils/block.rs
block-producer/src/test_utils/store.rs
block-producer/src/txqueue/mod.rs
block-producer/src/txqueue/tests/mod.rs

The main code base didn't need the reference counting, and could be implemented with slices only. So this PR removes the `Arc<T>`s in favor of borrowing. The idea is that the types are a bit more straight forward (less wrappers), and we save a bit in atomic counting (not that important, most likely negligible).

block_builder: using borrows instead of refcount

---

block-producer/src/txqueue/mod.rs

this behavior is a bit surprising, i think it deserves a small comment.

txqueue: document where empty blocks come from

---

block-producer/Cargo.toml
block-producer/src/batch_builder/batch.rs
block-producer/src/txqueue/mod.rs
block-producer/src/txqueue/tests/mod.rs

The test `test_build_batch_success` was flaky on the CI because of lack of coordination among the test and the code. This commit fixes the issue by using tokio's paused time loop, with explicity time advances, and a channel to synchronize the batch builder task with the test.
additional details on https://github.com/0xPolygonMiden/miden-node/pull/201 and https://github.com/0xPolygonMiden/miden-node/pull/202

block_builder: fix flaky tests (fixes: #125)

---

.gitignore
block-producer/src/state_view/mod.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/store/mod.rs

The checks that were performed on new txs received by the node were preventing new accounts to submit txs. 
Because the `account_hash` of the tx account did not match the `account_hash` contained in the DB for this specific tx account considering that it had never be added. 
By default it was `Digest::default()`
Closes: #176

Fix failed verification for new accounts

---

Cargo.toml
block-producer/Cargo.toml
block-producer/block-producer-example.toml
block-producer/src/block_builder/tests.rs
block-producer/src/config.rs
block-producer/src/errors.rs
block-producer/src/server/api.rs
block-producer/src/server/mod.rs
block-producer/src/state_view/mod.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/txqueue/mod.rs
block-producer/src/txqueue/tests/mod.rs
node/miden-node.toml
node/src/commands/start.rs
rpc/Cargo.toml
rpc/src/server/api.rs

In this PR I propose the addition of the verification of tx proofs on the `RPC` and `Block Producer` of the Miden node.
This will make sure that the locally proven tx's have a valid proof of execution.
Closing: #106 
Would be better to merge after: https://github.com/0xPolygonMiden/miden-base/pull/460

Add tx proof verification in `RPC` and `Block Producer`

---

block-producer/src/state_view/mod.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/test_utils/account.rs

In this PR I propose to remove the TODO that checks if the transaction was executed against a new account.
I made sure that the transactions initial account hash is indeed equal to `Digest::default()` considering that we received `None` back from the store, meaning that this is a new account.

Fix `TODO` for new accounts

---

Cargo.toml
block-producer/Cargo.toml
node/src/commands/genesis/mod.rs

In this PR I propose to set the nonce of Miden-Accounts imported at genesis to 1. 
This will prevent errors that we had on checks because of accounts imported at genesis breaking the node constraints.
Closes: #223

Set nonce of accounts to 1 at genesis

---

block-producer/Cargo.toml
block-producer/src/block_builder/prover/block_witness.rs
block-producer/src/block_builder/prover/mod.rs
block-producer/src/block_builder/prover/tests.rs
block-producer/src/block_builder/tests.rs
node/src/commands/genesis/mod.rs
proto/src/domain/blocks.rs
proto/src/domain/mod.rs
store/src/db/sql.rs
store/src/genesis.rs
store/src/state.rs

This PR updates the code to be compatible with new 0.8 version of the Winterfell.
This update mostly contains changes in `Felt` creation, since casting of `u64` to `FieldElement` was removed. It also updates the serialization and deserialization of the structs, which contain vectors of `Felt`s or `RpoDigest`s.

Update code to be compatible with Winterfell 0.8

---

block-producer/src/block.rs
block-producer/src/block_builder/prover/block_witness.rs
block-producer/src/block_builder/prover/tests.rs
block-producer/src/errors.rs
block-producer/src/store/mod.rs
block-producer/src/test_utils/block.rs
block-producer/src/test_utils/store.rs
proto/src/domain/blocks.rs
proto/src/errors.rs
proto/src/lib.rs

This PR addresses comment: https://github.com/0xPolygonMiden/miden-node/pull/208#discussion_r1485563945
Moved `BlockInputs` to block-producer, converted accounts and nullifiers to binary-tree maps.

`BlockInputs` improvements

---

block-producer/Cargo.toml
block-producer/src/batch_builder/mod.rs
block-producer/src/server/mod.rs
block-producer/src/txqueue/mod.rs
node/Cargo.toml
rpc/src/server/mod.rs
store/src/server/mod.rs
utils/src/logging.rs

Fixed a few issues I found with the logging and also fixes #231 while I was at it.
- Remove the spans that would swallow all the logs when using tracing forest. These were the spans around main and tasks' entry points.
- Added feature flags to enable tracing_forest. The previous approach did not work, since the compilation profile doesn't change the dependencies.
- Added support for `RUST_LOG` and changed the default from `TRACE` to `INFO`.

tracing_forest: fixed issues to use logging with dev envs

---

block-producer/src/batch_builder/tests/mod.rs
block-producer/src/block_builder/prover/tests.rs
block-producer/src/block_builder/tests.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/state_view/tests/mod.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/test_utils/mod.rs
block-producer/src/test_utils/proven_tx.rs
block-producer/src/txqueue/tests/mod.rs

In this PR we got rid of `DummyProvenTxGenerator` in favour of `MockProvenTxBuilder`. The latter was also improved in order to provide all needed features.
Look into https://github.com/0xPolygonMiden/miden-node/issues/79 for context.

Mock proven TX improvements

---

Cargo.toml
block-producer/Cargo.toml

This small PR changes Miden VM crates dependencies from git link to crate version.
This PR should be merged after https://github.com/0xPolygonMiden/miden-base/pull/486.

Change git VM dependency to crate version

---

block-producer/src/batch_builder/tests/mod.rs
block-producer/src/block_builder/prover/tests.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/state_view/tests/mod.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/test_utils/batch.rs
block-producer/src/test_utils/proven_tx.rs
block-producer/src/txqueue/tests/mod.rs

This addresses comment from here: https://github.com/0xPolygonMiden/miden-node/pull/248#discussion_r1502794786

Got rid of shared state in `MockProvenTxBuilder`

---

block-producer/src/batch_builder/batch.rs
block-producer/src/block_builder/prover/block_witness.rs
block-producer/src/block_builder/prover/mod.rs
block-producer/src/block_builder/prover/tests.rs
block-producer/src/block_builder/tests.rs
block-producer/src/errors.rs
block-producer/src/state_view/tests/apply_block.rs
block-producer/src/state_view/tests/verify_tx.rs
block-producer/src/test_utils/block.rs
block-producer/src/test_utils/proven_tx.rs
block-producer/src/test_utils/store.rs
store/src/state.rs

- `MockStoreSuccessBuilder` and `build_expected_block_header()` now compute produced notes root
- `MockStoreSuccessBuilder::new()` was replaced with two constructors: `from_batches` and `from_accounts` which allow it to fill initial account IDs and state and also nullifiers and produced notes.
This will resolve #79

Improvements in `MockStoreSuccessBuilder`

---

.github/ISSUE_TEMPLATE/1-bugreport.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/3-task.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

This adds issue templates. The goals here are:
- Make sure that we communicate what we want in the issue. The goal is for the issue to have enough context so that another dev can pick the issue up and start working on it.
- Add structure to issues when opened by people outside of the team. The goal is to make the issue template structure in such a way it is helpful for us to understand the external request, and to help any external contributor to give us the context we need to understand the issue/feature.
---
GH has moved away from the markdown templates to yaml based templates. So this PR is using the later. The syntax is [documented here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema).
I have kept the …

gh: add issue templates

---

.github/ISSUE_TEMPLATE/3-task.yml

I found a issue with the task template. Maybe this is the reason why it is not rendering.
There should also be a issue template validation somewhere, at least the errors are [documented here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms). But I couldn't find the tool, I guess it is only available for the repo's admins.
Edit: Ahhhh, that was simple. I just had to navigate to the yaml file:
And yeah, the issue was the lack of a `label` in there.

gh: fix task template

---

block-producer/src/block_builder/mod.rs
proto/src/domain/mod.rs
proto/src/lib.rs
store/src/state.rs

This bug leaded to incorrect checking of already consumed notes.
This will resolve #249

Fixed `nullifier_value_to_block_num` function

---

store/src/db/mod.rs
store/src/db/sql.rs
store/src/db/tests.rs
store/src/errors.rs
store/src/lib.rs
store/src/nullifier_tree.rs
store/src/server/api.rs
store/src/state.rs

Resolves: https://github.com/0xPolygonMiden/miden-node/issues/269

Implemented nullifier tree wrapper over `Smt`

---

.gitignore
docs/index.md
mkdocs.yml
requirements.txt
run.sh

This PR adds the mkdocs-material skeleton.
- Run the `run-docs-site.sh` script to bring up the side.
- Create new markdown content in the docs folder.
- Add new pages to the nav section in the `mkdocs.yml` file.

Setting up the mkdocs-material skeleton for this repo

---

store/src/db/migrations.rs

The table in the references clause had a typo.

bugfix: table name is block_headers instead of block_header

---

Cargo.lock
store/Cargo.toml
store/src/db/migrations.rs
store/src/db/tests.rs

I'm not sure why the PRAGMA wasn't sufficient. But this was caught by @phklive when integrating the faucet. The feature flag seems to be required

sqlite: use bundled version to enable FK checks

---

.github/workflows/doc.yml
.github/workflows/lint.yml
.github/workflows/test.yml

[As it was done for the miden-client workflows](https://github.com/0xPolygonMiden/miden-client/pull/222/files), this PR replaces the usage of `actions-rs/toolchain` which is archived as of now with the updated `dtolnay/rust-toolchain` action.

chore: update archived action on ci

---

store/src/db/migrations.rs

We found the following error logged on the node when running the integration tests in parallel:
```
2024-04-05T17:42:29.402418Z ERROR apply_block: miden-store: store/src/db/mod.rs:239: error: SQLite error: UNIQUE constraint failed: notes.block_num, notes.note_index
2024-04-05T17:42:29.402427Z ERROR store:apply_block:apply_block: miden-store: store/src/state.rs:104: error: Block applying was broken because of closed channel on database side: channel closed
```
apparently on #295 we changed the block's note tree to also use the note's batch. In there we included the note's batch index. The error from above is because the note's table on the db still has (block_num, note_index) as a primary key so two notes from different batches might conflict with each other.
- clone the miden-client repo …

fix: include batch index in db constraint for notes

---

store/src/db/sql.rs

when running integration tests for onchain accounts we stumbled upon this error:
```bash
thread 'tokio-runtime-worker' panicked at store/src/db/sql.rs:176:17:
assertion failed: account.is_new()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-04-10T17:43:27.830234Z  INFO write_block_to_db: miden-store: store/src/db/mod.rs:290: close, time.busy: 418µs, time.idle: 18.3µs
2024-04-10T17:43:27.830332Z ERROR apply_block: miden-store: store/src/db/mod.rs:275: error: SQLite pool interaction task failed: Apply block task failed: Panic
2024-04-10T17:43:27.830331Z ERROR store:apply_block:apply_block: miden-store: store/src/state.rs:107: error: Block applying was broken because of closed channel on database side: channel closed
```
The culprit is the check:
```rust …
```

fix: remove assert when producing block for new onchain account

---

node/src/commands/genesis/mod.rs
proto/proto/note.proto
proto/src/generated/note.rs
store/src/db/mod.rs
store/src/db/sql.rs
store/src/db/tests.rs
store/src/server/api.rs
store/src/state.rs

Basing it off of `phklive-block-producer-onchain` to make it simpler to test from the client.

Add note type to `NoteSyncRecord`

---

.github/workflows/deb_packager.yml
README.md
packaging/genesis.toml
packaging/miden-node.service
packaging/miden.toml
packaging/postinst
packaging/postrm

Adding debian packager for amd64
Checksum function for package
Updated Readme.md for packages and checksum
Added packager directory, contains postinst, postrm, and cloned copy of the toml files for miden. Note, these are just place holders and they should be adjusted.
Created service file. 
Tested on Ubuntu 22

Adding amd64 debian packager, checksums, README updates.

---

block-producer/src/batch_builder/batch.rs

Since miden-base fix was merged, we can simplify the code and remove `TODO`.

Used `OutputNote::metadata` and removed `TODO`

---

crates/block-producer/src/test_utils/proven_tx.rs
crates/store/src/db/migrations/001-init.sql
crates/store/src/db/sql.rs

Resolves: https://github.com/0xPolygonMiden/miden-node/issues/301

Renamed `note_hash` to `note_id`

---

CHANGELOG.md
crates/proto/proto/requests.proto
crates/proto/proto/responses.proto
crates/proto/src/generated/requests.rs
crates/proto/src/generated/responses.rs
crates/rpc/README.md
crates/store/README.md
crates/store/src/errors.rs
crates/store/src/server/api.rs
crates/store/src/state.rs

feat: Return block authentication data with `GetBlockHeaderByNum`

---

crates/proto/src/generated/requests.rs
crates/proto/src/generated/responses.rs
crates/rpc/src/server/api.rs

This small PR makes is so that we return more detailed error messages from the PRC when proof verification fails.

Make proof verification error messages more detailed in the RPC

---

bin/faucet/src/static/index.html

Addresses changes following https://github.com/0xPolygonMiden/miden-client/issues/314, which changed the name of the client into `miden`

docs: Rename client binary name

---

crates/store/src/blocks.rs
crates/store/src/db/mod.rs
crates/store/src/state.rs

I noticed that after refactoring, block saving, which is blocking, was moved from background thread to the async runtime. This can affect other async tasks, so I implemented async method as well. Unfortunately we can't simply get rid of blocking method now, since it is used in synchronous runtime (in genesis block storing).

Save blocks asynchronously

---

crates/rpc/src/server/mod.rs

on #352 we added support for webrpc, but it causes the node to not start as it has the route definitions duplicated. I tested removing the line and running the miden client's integration test to make sure we're still supporting http2 requests.

fix: remove duplicate rpc server

---

Cargo.lock
bin/faucet/Cargo.toml
bin/faucet/src/handlers.rs
bin/faucet/src/utils.rs

Migrates faucet's revisions to the newer ones.
As a consequence of changes in how the store is handled between the client and `miden-base`'s `TransactionExecutor`, it is not `Send` and so a `Client` is instantiated on each request for now (which might be a net positive for how the faucet is supposed to work at least?).

feat: Use newer revisions for faucet

---

bin/node/src/commands/genesis/inputs.rs
bin/node/src/commands/genesis/mod.rs
config/genesis.toml
crates/store/src/genesis.rs

closes #305.
changes:
- added the possibility to specify whether the genesis accounts are on_chain or not. If not specified defaults to false ([11994b6](https://github.com/0xPolygonMiden/miden-node/pull/365/commits/11994b60dffd25118db344b2e00be0afe702514e))
- changed the `into_block` function of `GenesisState` so it choses the appropiate `AccountUpdateDetails` ([7bcfe25](https://github.com/0xPolygonMiden/miden-node/pull/365/commits/7bcfe25806dce9c621b67b35e612cb97422fd652))
1. initialize two miden clients
2. create a new genesis uncommenting the `on_chain = true` lines in the config for both accounts
3. start the node
4. import the accounts on each client
5. run a mint transaction on one of the clients, wait for a bit so the tx gets included in a block and sync on the other client. You …

feat: add config to make onchain genesis accounts

---

crates/block-producer/src/block_builder/prover/block_witness.rs

We found that the integration tests on the client were sometimes failing after the recent changes related to adding the transactions to the block structures. @mFragaBA investigated a bit and saw that the node was logging an `InvalidTxHash` error which implied problems with checking the consistency between the header and the block's transactions, concluding that the tests were flaky because this would only occur when a couple of transactions for different accounts are batched into the same block. This is because the `BlockWitness` keeps the transaction data in a `BTreeMap`, which breaks ordering with the iterator. There are structs that would preserve it while providing dictionary functionality, but in this case it seems we can just replace it with a `Vec`.
Ran the tests with these changes …

fix: Preserve transaction ordering in `BlockWitness`

---

CHANGELOG.md
crates/store/src/db/migrations/001-init.sql
crates/store/src/db/sql.rs
crates/store/src/errors.rs

addresses #342.
I tried testing this using the integration tests on miden-client but they fail because I still can't use any other value than 0 for the aux field until https://github.com/0xPolygonMiden/miden-base/issues/731 is done. 
That being said, I somewhat tested this change by changing the hardcoded 0 value in the transaction kernel's create_note and using the same value for notes on the integration tests. They ran successfully with some fixes present in https://github.com/0xPolygonMiden/miden-client/pull/381 (mainly removing hardcoded values from the client side)
- the client was able to consume the notes
- I checked the node's db using `sqlite3` and the aux column of `notes` had the proper values

feat: store and retrieve aux field

---

CHANGELOG.md
Cargo.lock
bin/faucet/src/client.rs
bin/faucet/src/transaction_scripts/distribute_fungible_asset.masm
crates/store/src/db/tests.rs

With the [recent change](https://github.com/0xPolygonMiden/miden-base/pull/752) in `miden-base` the faucet stopped working. This PR fixes the note script the faucet uses to send assets.

fix: Add `aux` input to faucet

---

README.md

Fix the links to `rpc`, `store`, `block_producer` crates in the Readme.

docs: fix invalid links in the Readme

---

CHANGELOG.md
Cargo.lock
bin/faucet/Cargo.toml
bin/faucet/README.md
bin/faucet/src/config.rs
bin/faucet/src/main.rs
bin/node/Cargo.toml
bin/node/src/commands/genesis/inputs.rs
bin/node/src/commands/genesis/mod.rs
bin/node/src/commands/init.rs
bin/node/src/commands/mod.rs
bin/node/src/config.rs
bin/node/src/main.rs
crates/block-producer/src/config.rs
crates/rpc/src/config.rs
crates/store/src/config.rs
crates/utils/src/config.rs

closes #385
This PR adds `init` commands in the node and faucet to generate default configuration files.
- `miden-node init` creates both "miden-node.toml" and "genesis.toml".
- `miden-faucet init` creates "miden-faucet.toml".

feat: Add init commands

---

Cargo.lock
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/batch_builder/tests/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/block_builder/tests.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/test_utils/batch.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/txqueue/tests/mod.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql.rs
crates/store/src/server/api.rs
crates/store/src/state.rs

This PR is created in order to address remaining review comments in https://github.com/0xPolygonMiden/miden-node/pull/390. We had to merge that PR in order to make miden-note compilable against the latest miden-base.
Here we remove in-memory notes map in favor of direct queries to database. Output notes consumed in the same batch now removed from output notes list and SMT, corresponding input notes also removed from a batch and don't affect produced nullifiers set. Input unauthenticated notes are checked for duplicates as well, as output notes. Hashes of all corresponding output/input notes are required to be equal.
Resolves: https://github.com/0xPolygonMiden/miden-node/issues/381

Addressed review comments for #390

---

Cargo.toml
bin/faucet/Cargo.toml
bin/node/Cargo.toml
crates/block-producer/Cargo.toml
crates/proto/Cargo.toml
crates/rpc-proto/Cargo.toml
crates/rpc/Cargo.toml
crates/store/Cargo.toml
crates/utils/Cargo.toml

This removes the need to edit each crate's toml file when bumping the version.
This is under the assumption that these are always in lockstep.

chore: use workspace inheritance for crate versions

---

CHANGELOG.md
bin/faucet/src/config.rs
bin/faucet/src/main.rs
bin/node/src/commands/genesis/mod.rs
bin/node/src/commands/start.rs
bin/node/src/config.rs
bin/node/src/main.rs
config/miden-node.toml
crates/block-producer/src/config.rs
crates/rpc/src/config.rs
crates/store/src/config.rs
crates/utils/src/config.rs

Simplifies node configuration by removing all redundant options.
The following options are removed 
- block_producer.store_url
- rpc.store_url
- rpc.block_producer_url
as they are already covered by `store.endpoint` and `block_producer.endpoint`.
Note that this only impacts the configuration options as seen by the caller of the node binary. Individual node components (rpc, store, block_producer) still have the original configuration objects. This PR only strips out the duplicate options for the user.
In addition, this PR removes the optional indirection in `NodeConfig`. ~Maybe this is incorrect, and the `figment` crate somehow requires this to handle missing options properly? I don't think so; but maybe there was a reason for this beyond old changes :)~
Closes #334. …

feat(node): normalize configuration

---

CHANGELOG.md
crates/block-producer/src/state_view/mod.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/store.rs

Improve the type safety of `TransactionInputs::nullifiers` mapping by using `Option<NonZeroU32>` instead of relying on zero to indicate none.
Shower thought: is there utility in allowing a nullifier set to be included in the genesis block? Maybe for bootstrapping test networks..
(I'm happy to also just drop this PR, its not a major thing)

feat(block-producer): nullifier map type safety

---

CHANGELOG.md
Cargo.lock
bin/faucet/Cargo.toml
bin/faucet/build.rs
bin/faucet/src/main.rs
bin/faucet/src/static/index.js

This PR simplifies faucet deployment by embedding the website within the binary. This removes the need to separately deploy the website resources.
To facilitate this, this PR also fixes a paper-cut with the javascript callbacks. Previously these were hardcoded to use `localhost:8080` as the server address. These would have to be manually edited to the correct URL (which might be a proxy) during deployment. Instead we now use `window.location.href` which gives the correct url of the current page.
Note: I am not a web expert so if anyone has any input on the above that would be welcome.
------------------------
The static embedding is handled using a build script + additional dependencies, which I dislike but it seems this is the "blessed" way to achieve this using `actix-web`.
I tested …

feat(faucet): embed static website

---

README.md

Updates the README by adding the `miden-node init` command before running the genesis.

docs(README): improve configuration files documentation

---

crates/proto/build.rs
crates/rpc-proto/build.rs

Build scripts for code generation from *.proto files depend on `BUILD_PROTO` environment variable. But when user sets value of this variable to "1" after previous run, build scripts runs are skipped. This PR fixes that.

Rerun build scripts for protobuf on env changed

---

.github/workflows/changelog.yml
Cargo.lock
Cargo.toml
bin/faucet/src/client.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/state_view/mod.rs
crates/block-producer/src/test_utils/proven_tx.rs
crates/block-producer/src/test_utils/store.rs
crates/store/src/db/migrations/001-init.sql
crates/store/src/db/mod.rs
crates/store/src/server/api.rs
crates/store/src/state.rs

This PR updates the miden-base dependencies to the current `next` branch tip.
#407 is currently blocked by the recently merged [PR in `base/miden-objects`](https://github.com/0xPolygonMiden/miden-base/pull/797). This PR unblocks #407 by updating our dependencies to include it.
I opened this as a separate PR since there are some associated changes that need reviewing.
I'm also unsure of the cross-repo update procedure so maybe this is the wrong way of doing it.
Lastly, probably we don't want to track `next` so I've specified the current latest commit.
-------------------------
This PR also added an unrelated fix to the changelog workflow which could be pulled into a separate PR if we want this to remain more "pure". See [this comment](https://github.com/0xPolygonMiden/miden-node/pull/416#is …

feat: update miden-base dependencies

---

CHANGELOG.md
bin/node/src/commands/genesis/inputs.rs
bin/node/src/commands/genesis/mod.rs

Resolves: https://github.com/0xPolygonMiden/miden-node/issues/198
With this PR user won't be forced to create at least one account in genesis. Also I slightly changed behavior working with `accounts` directory during genesis creation: if this directory already exists, program will fail. If `--force` flag is provided, directory will be overwritten.

Make accounts optional for genesis generation

---

CHANGELOG.md
crates/proto/src/generated/requests.rs
crates/proto/src/generated/responses.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/store.rs
crates/rpc-proto/proto/requests.proto
crates/rpc-proto/proto/responses.proto
crates/rpc-proto/proto/rpc.proto
crates/rpc-proto/proto/store.proto
crates/rpc/src/server/api.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql.rs
crates/store/src/db/tests.rs
crates/store/src/server/api.rs
crates/store/src/state.rs
proto/requests.proto
proto/responses.proto
proto/rpc.proto
proto/store.proto

closes #404
This is my first time implementing something in the node, I originally made this to better understand the node internals. Be sure to correct me if I missed something important in terms of validation or security.
This PR looks to add a new endpoint to the node that lets users check if a note is consumed without directly exposing its nullifier. In the next hours I'll also be adding a PR in the client that uses this endpoint to deal with imported notes.

feat: implement `CheckNullifiersByPrefix` endpoint

---

CHANGELOG.md
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/tests/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/block_builder/prover/block_witness.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/state_view/account_state.rs
crates/block-producer/src/state_view/mod.rs
crates/block-producer/src/state_view/tests/apply_block.rs
crates/block-producer/src/state_view/tests/verify_tx.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/txqueue/tests/mod.rs

Support multiple inflight transactions affecting the same account by tracking the latest inflight state of modified accounts. This is then checked against new txns.
This is likely more a progress check than a final PR - I suspect there are more indirect changes that must be made?
Probably missing: tests ensuring that secondary inflight transactions are rejected if they have the wrong initial state.
Closes #186

feat(block-producer): multiple inflight account txs

---

CHANGELOG.md
crates/store/src/db/mod.rs
crates/store/src/db/sql.rs
crates/store/src/lib.rs

Replace all `conn.prepare` with `conn.prepare_cached` and double the cache size limit from the [default of 16](https://docs.rs/rusqlite/latest/src/rusqlite/lib.rs.html#152) to 32. We currently have 22 different statements so this should be adequate for a while.
Closes #423.

feat(store): cache sql statements

---

CHANGELOG.md
crates/block-producer/src/batch_builder/batch.rs
crates/proto/src/generated/requests.rs
crates/proto/src/generated/responses.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/store.rs
crates/rpc-proto/proto/requests.proto
crates/rpc-proto/proto/responses.proto
crates/rpc-proto/proto/rpc.proto
crates/rpc-proto/proto/store.proto
crates/rpc/src/server/api.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql.rs
crates/store/src/errors.rs
crates/store/src/server/api.rs
crates/store/src/state.rs
proto/requests.proto
proto/responses.proto
proto/rpc.proto
proto/store.proto

Closes #409.
The implementation is essentially a clone of SyncState with some parts left off. Which makes me believe I've misunderstood the assignment :)

feat(rpc): `SyncNotes` endpoint

---

CHANGELOG.md
Cargo.lock
bin/faucet/src/handlers.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/test_utils/proven_tx.rs
crates/proto/src/domain/notes.rs
crates/proto/src/generated/note.rs
crates/rpc-proto/proto/note.proto
crates/store/src/db/migrations/001-init.sql
crates/store/src/db/sql.rs
crates/store/src/db/tests.rs
proto/note.proto

This fixes the faucet's and node build by doing the following:
- Adding the new NoteExecutionHint for all note's metadata
- Adding the new after_block_num field to note exports on the faucet
- Adding the `execution_hint` field to Notes table.
Closes #439 .
This PR is built on top of https://github.com/0xPolygonMiden/miden-base/pull/827 .
It is meant to be merged AFTER that PR.

feat: Add note `execution_hint` to store

---

crates/proto/src/generated/responses.rs
crates/rpc-proto/proto/responses.proto
proto/responses.proto

Seems like the doc comments for the returned MMR path in the `SyncNoteResponse` was referring to an `MmrProof`, but a `MerklePath` is returned instead.

docs: Update `responses.proto`

---

.github/workflows/deb_packager.yml
.github/workflows/doc.yml
.github/workflows/lint.yml
.github/workflows/test.yml
Makefile
bin/node/Dockerfile

This PR adds `--locking` to all infrastructure files where applicable. It also removes all `nightly` toolchains from non-fmt workflows.
Closes #447.

ci: add locking and remove extra nightly

---

.github/workflows/deb_packager.yml

I broke this in #448.
This workflow also has some strange triggers. Should we remove some of them?
I somehow thought it should only run for formal releases.
-------------------
edit: workflow now only triggers on releases

ci: fix debian package workflow

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/faucet/src/client.rs
crates/block-producer/Cargo.toml
crates/block-producer/src/block_builder/prover/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/test_utils/proven_tx.rs
crates/store/src/db/tests.rs
rust-toolchain.toml

This PR updates `miden-base` (and related `miden-vm` and `winterfell`) dependencies to the latest version. It also increases MSRV to 1.80.

Update miden-base dependencies to latest

---

Cargo.lock
crates/block-producer/Cargo.toml
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/block.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/store.rs
crates/proto/src/domain/notes.rs
crates/store/src/server/api.rs
crates/store/src/state.rs

Decouple `store` from `block-producer`. The only remaining item was `NoteAuthenticationInfo` which I moved into the `proto` crate.
Closes #455

chore(block-producer): drop store depedency

---

bin/faucet/src/client.rs
bin/faucet/src/handlers.rs
bin/faucet/src/main.rs
bin/faucet/src/transaction_scripts/distribute_fungible_asset.masm
crates/block-producer/src/server/api.rs
crates/block-producer/src/state_view/mod.rs
crates/block-producer/src/state_view/tests/apply_block.rs
crates/block-producer/src/state_view/tests/verify_tx.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/store.rs
crates/block-producer/src/txqueue/mod.rs
crates/block-producer/src/txqueue/tests/mod.rs
crates/proto/src/generated/responses.rs
crates/rpc-proto/proto/responses.proto
crates/store/src/server/api.rs
proto/responses.proto

This PR introduces a `current_block_number` to the `FaucetClient` and spawns a thread while running the faucet that is in charge of updating the `current_block_number` after `CHAIN_TIP_UPDATER_INTERVAL` time.
This PR also addresses an issue with the `.masm` file adding the execution hint field.
Closes #440

feat(faucet): add `after_block_num` to the faucet

---

CHANGELOG.md
crates/store/src/db/mod.rs
crates/store/src/db/sql.rs
crates/store/src/db/tests.rs
crates/store/src/server/api.rs

Resolves https://github.com/0xPolygonMiden/miden-node/issues/309
Introduced `NoteSyncRecord` domain type which omits note details unnecessary for state synchronizations. Refactored code, removed excessive function (`select_notes_since_block_by_tag_and_sender` can work as `select_notes_since_block_by_tag` if we provide empty sender list).

Removed note details from sync responses

---

CHANGELOG.md
crates/proto/src/generated/responses.rs
crates/rpc-proto/proto/responses.proto
crates/store/src/server/api.rs
proto/responses.proto

When updating the dependencies in the client we started getting this error when generating the rust types from proto files:
```
Error:   × name 'account.AccountInfo' is shadowed
╭─[responses.proto:164:5]
163 │     // Account info (with details for on-chain accounts)
164 │     account.AccountInfo account = 1;
·     ─────────┬─────────
·              ╰── found here
165 │ }
╰────
help: 'account.AccountInfo' is is resolved to
'responses.GetAccountDetailsResponse.account.AccountInfo',
which is not defined. The innermost scope is searched first
in name resolution. Consider using a leading '.'(i.e.,
'.account.AccountInfo') to start from the outermost scope.
```
It seems the name of the field `account` is shadowing the name of the import `account`. As it is recommended in the message, this can be …

fix: type shadowing in proto file

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/node/Cargo.toml
bin/node/src/commands/start.rs
bin/node/src/main.rs
crates/block-producer/Cargo.toml
crates/block-producer/src/server/mod.rs
crates/rpc/Cargo.toml
crates/rpc/src/server/mod.rs
crates/store/Cargo.toml
crates/store/src/server/mod.rs

I need a better word for `coherent` I think.
This PR improves the node component startup procedure. Instead of 
> spawning a component's rpc server and then waiting an arbitrary amount of time before deciding the server is "probably up"
we now separate out an initialization step before spawning the server. This init step includes binding a listener on the endpoint so that dependent components can begin connecting after init, but before serving has been spawned. In this way we can now know that after `Component::load` completes that we are safe to depend on the endpoint. 
Fixes #486.
Note: this is PR'd into `main` and not `next` as we require this fix for v0.5.1 as existing instances are currently unable to be restarted (see #483).
I manually tested this by inserting a 5s sleep before the …

feat: component startup is now coherent

---

crates/proto/src/domain/digest.rs

`TryFrom` implementation called `T::try_into` instead of `(*T)::try_into()` causing an infinite loop as both `T` and `&T` have this implemented.
This was introduced as part of a manual clippy fix (by me) in #476 where `x.clone().try_into()` was manually changed to `x.try_into()` instead of the suggested  `(*x).try_into()`. Does not affect any existing releases.
Fixes #487.
---------------------------
Side note: I do think implementing `TryFrom` for both owned and reference variants an anti-pattern.

fix: infinite recursion in Digest::try_into

---

Cargo.lock
Cargo.toml

This PR updates the `miden-base` branch as the old one (`polydez-note-tree-refactor`) no longer exists.

fix: update `miden-base` branch in Cargo.toml

---

Cargo.lock
bin/faucet/src/client.rs
bin/faucet/src/config.rs
config/miden-faucet.toml
crates/store/src/db/tests.rs
crates/store/src/genesis.rs

Follows https://github.com/0xPolygonMiden/miden-base/pull/875

chore: Update to miden-base's next

---

README.md

The previous command fails with the following error:
```bash
error: the argument '--path <PATH>' cannot be used with '--git <URL>'
Usage: cargo install --locked --path <PATH> --branch <BRANCH> [CRATE[@<VER>]]...
For more information, try '--help'.
```
Removing the `--path` and using an specific crate fixed the issue.

docs: fix readme removing `--path` option from installing command

---

CHANGELOG.md
bin/node/src/commands/genesis/inputs.rs
bin/node/src/commands/genesis/mod.rs
config/genesis.toml

Resolves: https://github.com/0xPolygonMiden/miden-node/issues/446
In this PR we remove support of basic wallet creation in genesis config.

Dropped basic wallet account from genesis file

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/faucet/Cargo.toml
bin/faucet/src/client.rs
bin/faucet/src/config.rs
bin/faucet/src/errors.rs
bin/faucet/src/handlers.rs
bin/faucet/src/main.rs
bin/faucet/src/state.rs

Resolves: https://github.com/0xPolygonMiden/miden-node/issues/479

feat(faucet): migrate from actix to axum

---

CHANGELOG.md
crates/block-producer/src/block_builder/prover/asm/block_kernel.masm
crates/block-producer/src/block_builder/prover/block_witness.rs
crates/block-producer/src/block_builder/prover/mod.rs

This PR refactors the `BlockWitness`: it no longer uses the operand stack to provide the inputs to the VM, it uses only advice inputs instead. 
Closes: #78.

`BlockWitness`: pass inputs to the VM through the advice provider

---

CHANGELOG.md
crates/store/src/errors.rs
crates/store/src/server/api.rs
crates/store/src/state.rs

In this PR we improve error statuses returned by the some store API.
Initially it was needed by https://github.com/0xPolygonMiden/miden-node/issues/504 (I wanted to be able to process "account not in DB" errors), but finally it became unused due to changed solution. But it might make our API better, so I propose to keep these changes.

feat(store): improve errors

---

CHANGELOG.md
crates/proto/src/generated/requests.rs
crates/proto/src/generated/responses.rs
crates/rpc-proto/proto/requests.proto
crates/rpc-proto/proto/responses.proto
crates/store/src/server/api.rs
crates/store/src/state.rs
proto/requests.proto
proto/responses.proto

feat: Return code for FPI

---

crates/block-producer/Cargo.toml
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/errors.rs

This PR 
- fixes several unaddressed review comments from #515 
- distributes batch and block proving times randomly
- injects random failures into batch and block proving
Specifically, addresses [this](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1811182793), [this](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1811216651) and [this](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1811217975) comment.
Proving times are distributed normally from within a configurable range.
Failure rates are also similarly configurable, which completes one task from #519.

feat(block-producer): fix dangling review comments

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Makefile
bin/faucet/Cargo.toml
bin/faucet/src/client.rs
crates/block-producer/src/block_builder/prover/asm/block_kernel.masm
crates/block-producer/src/block_builder/prover/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/test_utils/store.rs
crates/store/src/state.rs
rust-toolchain.toml

This PR updates the code of the `miden-node` to work with a next v0.11 version of the `miden-vm` and next version of `miden-base`.

Migrate to `miden-vm` v0.11

---

crates/block-producer/src/mempool/batch_graph.rs
crates/block-producer/src/mempool/dependency_graph.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/mempool/transaction_graph.rs

This PR ports `BatchGraph` to use `DependencyGraph` as its foundation.
I implemented this by extending `DependencyGraph` to have a new `pending` stage, where the node exists but does not yet have an associated value. For batches this value is its proof i.e. `TransactionBatch`.
Effectively nodes now have a pending state, and must be promoted by passing in a value for it. I'm not 100% happy with the naming of things. Pending, promotions, processed, committed.
This model does not quite match the `TransactionGraph` lifecycle, however this was easy to adjust by having `TransacionGraph::insert` invoke both actions.
The main benefit of this is reducing the test surface.

feat(block-producer): refactor batch graph to use dependency graph

---

crates/block-producer/src/mempool/inflight_state/mod.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/mempool/transaction_graph.rs

This PR upgrades `InflightState` so that it tracks each transaction's state delta internally. We differentiate between committed and uncommitted transactions. The former cannot be reverted.
This means reverting or committing transactions now only requires passing in the transaction IDs, instead of requiring the full transaction data.
This enables making the inflight state more robust as it now differentiates between committed and uncommitted transaction IDs. Additional work is required to change the current panics into errors instead, though this is left to a future PR as it isn't high priority. Tracked in #537.
Essentially this works towards hardening the different components of the mempool individually so that we can pick up corruption/bugs as soon as possible.

feat(block-producer): inflight state custody of transaction data

---

crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/server/api.rs
crates/block-producer/src/state_view/mod.rs
crates/block-producer/src/store/mod.rs
crates/rpc/src/server/api.rs
crates/store/src/server/api.rs

Clippy issue https://github.com/rust-lang/rust-clippy/issues/12281 was fixed in v1.81. We now have MSRV of 1.82 allowing us to remove our workaround.
More specifically, `#[async_trait]` was triggering this lint, and as of 1.81 no longer does.
I did grep the repo for `blocks_in_conditions` and can confirm we have no other instances of it.

chore: re-enable blocks_in_conditions lint

---

crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/server/mod.rs

I think, creation of `SharedMempool` as separated structure doesn't give us any benefits, but makes code more complex. Proposed refactoring in this PR.
By the way, @Mirko-von-Leipzig,  do we need additional mutex here? https://github.com/0xPolygonMiden/miden-node/blob/9445ca2276b3ed5d02bf14928adb221fd274562b/crates/block-producer/src/server/mod.rs#L165-L171
According to comment, this can help with rate limiting and queuing of new transaction, but it seems to me that one mutex in `SharedMempool` is enough to do this job.

refactor(block-producer): simplify shared mempool

---

crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/test_utils/batch.rs

Blocked by PR #543.
Removes the unnecessary deep cloning of transaction data by utilising `Borrow`. The `TransactionBatch::new` implementation can probably be improved to reduce the amount of iteration occurring, but I'm delaying that until the dust settles on the mempool implementation.
Closes #531

feat(block-producer): borrow instead of cloning txs

---

crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/block_builder/prover/block_witness.rs
crates/block-producer/src/domain/transaction.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/lib.rs
crates/block-producer/src/mempool/batch_graph.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/mempool/transaction_graph.rs
crates/block-producer/src/server/mod.rs

This PR improves mempool configuration and simplifies the block-producer errors exposed during batch and block building.
Mempool configuration is now separated out into a builder, and constraint support is added as a sort of batch/block budget that gets exhausted during the batch/block selection. In other words, batches/blocks produced by the mempool are guaranteed to adhere to the limits placed on them, removing the need for asserting these errors in the building process.
I've removed the transaction data passing in the error variant, which was used by the previous FIFO implementation to return the failed transactions into the pool. This is no longer required as the mempool retains a copy of all inflight transactions.
We may still want to perform these checks in the builders regardless; …

feat(block-producer): improve mempool config

---

CHANGELOG.md
bin/node/src/config.rs
crates/rpc/src/config.rs
crates/utils/src/config.rs

Ref #403 
Added https support in the endpoints struct.
By default, all default calls are to `http` type only as expected for localhost.

feat: added https support in endpoint config

---

Cargo.lock
Cargo.toml
crates/block-producer/Cargo.toml
crates/block-producer/src/batch_builder/tests/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/block_builder/tests.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/state_view/tests/apply_block.rs
crates/block-producer/src/state_view/tests/verify_tx.rs
crates/block-producer/src/txqueue/tests/mod.rs
crates/proto/src/errors.rs
crates/rpc/Cargo.toml
crates/store/Cargo.toml
crates/store/src/db/tests.rs

Removed unused dependencies, updated errors, fixed compilation errors in order to make node compilable against latest `miden-base`.

chore: migrate code to the latest `miden-base`

---

Cargo.lock
crates/block-producer/Cargo.toml
crates/block-producer/src/mempool/batch_graph.rs
crates/block-producer/src/mempool/dependency_graph.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/server/mod.rs
crates/block-producer/src/test_utils/proven_tx.rs

This PR corrects the mempool's behaviour when batches are reverted.
More concretely, it fixes an issue where a child batch jobs weren't invalidated when their parent batch was reverted. This is fixed by actively tracking inflight batch jobs, and ignoring submitted jobs not part of this list.

fix(block-producer): handle reverted batches

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/node/src/config.rs
crates/block-producer/Cargo.toml
crates/block-producer/src/batch_builder/tests/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/block_builder/tests.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/mempool/inflight_state/mod.rs
crates/proto/src/errors.rs
crates/rpc/Cargo.toml
crates/rpc/src/config.rs
crates/store/Cargo.toml
crates/store/src/db/tests.rs
crates/utils/src/config.rs

Merge `next` into `next-block-producer` so that we can perform the reverse merge afterwards.
Doing this as a PR so we can sanity check the diff. Once CI passes I'll force push this into `next-block-producer`.

feat(block-producer): merge in next

---

crates/block-producer/src/lib.rs

Reduce block interval timer: `10s -> 5s`.
No changelog as the `10s` variant was never officially released.
Closes #564.

chore(block-producer): increase block frequency

---

bin/node/src/commands/genesis/mod.rs
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/state_view/tests/apply_block.rs
crates/block-producer/src/state_view/tests/verify_tx.rs
crates/block-producer/src/txqueue/tests/mod.rs
crates/proto/src/domain/digest.rs
crates/store/src/db/tests.rs
crates/store/src/nullifier_tree.rs

Removes the `test_` prefix applied to many of our test cases.
Tests are already annotated with `#[test]` and are usually inside a `mod tests` so also prefixing each test function is largely redundant.
Briefly discussed [here](https://github.com/0xPolygonMiden/miden-node/pull/563#discussion_r1872856703).

chore: remove `test_` prefix stutter

---

crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/server/mod.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/test_utils/mod.rs
crates/block-producer/src/test_utils/store.rs

This PR removes the block producer's `Store` and `ApplyBlock` traits.
Instead the methods are moved directly into the `DefaultStore` struct, which has also been renamed to a more appropriate `StoreClient`.
The traits were required to facilitate mocking as part of tests. Most of these usages were removed as part of the mempool work, which allowed these traits to largely just disappear.
There are still some remnants lurking (`MockStoreSuccess` et al), but these require larger refactors to the underlying tests. 
In general, we should avoid mocks where possible as its very easy for things to desync with reality. And indeed some of the above tests aren't actually testing the unit-under-test but rather the test setup code. Ideally we would have an actual in-memory store running for each test …

refactor(block-producer): remove Store traits

---

crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/mempool/batch_graph.rs
crates/block-producer/src/mempool/mod.rs

As mentioned in this [comment](https://github.com/0xPolygonMiden/miden-node/issues/397#issuecomment-2529077185), this PR makes it clear that batches within a block have a given order. This intention signaling is improved by using a vector instead of a map (with accidental ordering). As alluded to in [this comment](https://github.com/0xPolygonMiden/miden-node/issues/397) from #397.
> The [current](https://github.com/0xPolygonMiden/miden-node/blob/0f6b69af58189755d0ec9b13f994d3ef75317485/crates/block-producer/src/mempool/batch_graph.rs#L220-L247) batch selection strategy just selects an arbitrary available root batch. A root batch by definition is one who's parents have already been selected previously; or in other words dependency order is enforced within the selection process.
>
> The set …

refactor(block-producer): order batches within a block

---

crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/test_utils/batch.rs

This was previously added in #544 but was mistakenly dropped by a rebase.
Closes #531 (again).

feat(block-producer): remove deep clone of tx data

---

Cargo.lock
crates/proto/Cargo.toml
crates/proto/build.rs

Remove the final remnants of `miette` by replacing its usage in `proto::build.rs` with `anyhow`.
Motivation is to minimize our direct dependencies and there is not really an argument for `miette` as we don't have any source code errors to display.

chore: remove miette dependency

---

crates/block-producer/src/block.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/store.rs
crates/proto/src/errors.rs

This PR instruments the `StoreClient` API (follow-up task from #571), and also consolidates the errors into a single `StoreError` variant.
We should also create an issue for adapting the error guidelines discussed in https://github.com/0xPolygonMiden/miden-base/discussions/966.

refactor(block-producer): cleanup StoreClient

---

crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/mempool/batch_graph.rs
crates/block-producer/src/mempool/mod.rs

This PR replaces the `BatchId` type alias with a new type, and then uses this instead of `BatchJobId` to track batches within the mempool. This will prepare us for when such a ty
I have reservations about doing this as it forces the computation of `BatchId` to occur within the mempool's lock. Since this is hash over all transaction IDs this will be computationally expensive especially in comparison to all other operations in the mempool. 
Completes a task in #519 (Use a more correct BatchId)

refactor(block-producer): replace BatchJobId with BatchId

---

Cargo.lock
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/server/api.rs
crates/block-producer/src/server/mod.rs
crates/block-producer/src/state_view/mod.rs
crates/block-producer/src/store/mod.rs
crates/rpc/src/server/api.rs
crates/store/src/db/migrations.rs
crates/store/src/db/mod.rs
crates/store/src/server/api.rs
crates/store/src/state.rs

This PR adds tracing instrumentation to the mempool.
In addition, this PR also bumps `tracing` to v0.14 which now allows using constants for instrument targets. Before this we've had the unfortunate situation of using `target = COMPONENT` when emitting events, but having to manually set `target = miden-node-<xxx>` when using the `#[instrument]` macro. This PR fixes this; though I think our behaviour here could be improved.
Blocked by #577 as it refactors batch ID, and by #574 which added instrumentation which will require a minor tweak or two in this PR.
Closes a task in #519

feat(block-producer): instrument mempool

---

README.md

Was setting up the miden-node and came across this small issue in the README. This PR is to update command in README from `--input-path` to `--inputs-path`.
The command in the CLI: https://github.com/0xPolygonMiden/miden-node/blob/944d589bef23449dcb56f16702211c1699be4d5b/bin/node/src/main.rs#L50

Update command in README to `--inputs-path` when creating genesis file

---

crates/block-producer/README.md

Changes:
one of components → one of the components
Submits proven → Submits a proven
Why it’s useful:
These fixes improve the readability and accuracy of the documentation/code, making the text clearer and more grammatically correct.

docs(block-producer): typos in readme

---

CHANGELOG.md
crates/block-producer/src/domain/transaction.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/store.rs
crates/proto/src/generated/responses.rs
crates/rpc-proto/proto/responses.proto
crates/store/src/server/api.rs
crates/store/src/state.rs
proto/responses.proto

This PR inverts `TransactionInputs.missing_unauthenticated_notes` to `found_authenticated_ntoes`.
Closes a task from #519.

refactor(rpc): invert tx inputs missing notes to found

---

crates/block-producer/src/block_builder/mod.rs

This PR changes the behaviour when a block tick is missed from `Delay` to `Burst`.
#523 discusses this is slightly more detail:
> Burst will let us catch up lost blocks, but will have the least predictable block times while this is happening. Essentially blocks are produced as fast as possible.
>
> Skip will miss a block but keep the block publishing moment predictable. I'm not sure this matters.
>
> Delay means we only have a single slow block, and that block times are kept consistent.
`Burst` seems fine, and means we make the best attempt at the desired block interval on average.
Closed #523

feat(block-producer): catch up missed blocks instead of skipping

---

crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/server/mod.rs
crates/block-producer/src/store/mod.rs

This was removed as part of the mempool feature, but should not have been.
I've renamed the function `get_batch_inputs` and I'm wondering if we shouldn't rename the proto definition and domain object similarly?
I'm assuming there might be more input fields coming in the future so having it be more specific is ok?
Closes #566

feat(block-producer): re-add batch inputs

---

.github/actions/ssm_execute/action.yml
.github/workflows/deploy.yml

Fixes some issues picked up when deploying a non-release version.
Non-release deployments requires building the packages as part of the workflow. Release deployments simply pull the pre-built binaries from github directly. Non-release deployments haven't been exercised fully before.
More concretely this PR fixes:
- missing escape around the git reference input
- renames the built packages to those expected by the workflow
- missing line-ends of some ssm-command invocations

ci: fix deploy workflow

---

.github/actions/build_package/action.yml

- Fix typo in gitref variable name
- Add missing colons in error message syntax
- Refactor directory creation using loop to reduce code duplication

ci(deploy): fix gitref typo and simplify package directory creation

---

CHANGELOG.md
crates/proto/src/domain/accounts.rs
crates/proto/src/domain/digest.rs
crates/proto/src/domain/merkle.rs
crates/proto/src/domain/notes.rs
crates/proto/src/domain/nullifiers.rs
crates/proto/src/domain/transactions.rs
crates/store/src/db/mod.rs

Closes #454.
This PR aims to unify the aliases used for importing the protobuf types. When possible, referenced types like `proto::T.` If more than one type T is imported, the mod was used to locate it. For example: `proto::account::AccountId` and `proto::responses::AccountBlockInputRecord`.

style: standardize protobuf aliases

---

.github/workflows/amd_deb_packager.yml
.github/workflows/arm_deb_packager.yml
CHANGELOG.md
Makefile
README.md
bin/faucet/Cargo.toml
bin/faucet/README.md
bin/node/Cargo.toml
bin/node/Dockerfile

This PR removes the `--testing` feature.
This feature lowered the proof-of-work requirement to something more reasonable during this alpha period. It is no longer required due to changes in the protocol which reduced the proof-of-work required in proper production.
Closes #615

feat: remove `testing` feature

---

bin/faucet/src/client.rs
bin/faucet/src/errors.rs
bin/faucet/src/handlers.rs
bin/faucet/src/main.rs
crates/block-producer/src/batch_builder/batch.rs
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/block_builder/prover/block_witness.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/mempool/graph/mod.rs
crates/block-producer/src/server.rs
crates/proto/src/errors.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql/utils.rs
crates/store/src/errors.rs
crates/store/src/nullifier_tree.rs
crates/store/src/state.rs
crates/utils/src/errors.rs
crates/utils/src/logging.rs

Updates errors to follow the guidelines in https://github.com/0xPolygonMiden/miden-base/discussions/966.
This PR also removes the wildcard route option from the faucet. Currently the faucet allows visiting arbitrary paths (e.g. https://testnet.miden.io/asdas). Clearly this isn't behaving as intended and since we only have the single static file I've removed the wildcard entirely.
I looked into the axum defaults relating to https://github.com/0xPolygonMiden/miden-node/issues/499#issuecomment-2399190012 and decided the defaults of `Error` for failures, `Debug` for success are fine - though maybe we want to log the latter as info? I've also enabled the built-in axum rejects by setting `axum::rejections=trace` by default.
Closes #484, #499 and #581.
I do feel we could simplify our error …

refactor: standardize errors

---

Cargo.lock
bin/faucet/Cargo.toml
bin/faucet/src/errors.rs
bin/node/Cargo.toml
crates/block-producer/src/block_builder/prover/block_witness.rs
crates/block-producer/src/block_builder/prover/tests.rs
crates/block-producer/src/test_utils/account.rs
crates/store/src/db/tests.rs

Moves to latest base version which removes concurrent feature and changes initialization of account IDs.

chore: Move to latest base `next` and remove `concurrent` feature

---

.github/workflows/lint.yml
Cargo.lock
bin/faucet/Cargo.toml
bin/node/Cargo.toml

This PR adds CI job to reject unused dependencies using [cargo machete](https://github.com/bnjbvr/cargo-machete).
In addition this PR also removes two unused dependencies.

ci: check for unused dependencies

---

crates/block-producer/README.md
crates/proto/src/generated/requests.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/store.rs
crates/rpc-proto/proto/requests.proto
crates/rpc-proto/proto/rpc.proto
crates/rpc-proto/proto/store.proto
crates/rpc/README.md
crates/store/README.md
proto/requests.proto
proto/rpc.proto
proto/store.proto

This PR re-aligns the various RPC docs with the proto files.
I've opted to only provide a summary and not a full parameter doxygen style documentation as there was before as I don't think its trivial to keep aligned with reality, nor sufficient -- users will always have to use and/or read the proto files.
Closes #626

docs: align readme rpc docs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
LICENSE

This PR increments crate versions to v0.7.0 and updates `miden-base` dependencies to the crates.io versions.
Also, updated copyright year in the license file.

Prepare v0.7.0 release

---

Cargo.lock
Cargo.toml
bin/faucet/Cargo.toml
crates/block-producer/Cargo.toml
crates/utils/Cargo.toml

Closes #642
* Updates itertools and axum dependancy versions
* Adds itertools as a workspace dependancy
Noting that rusqlite must remain at 0.32.1 due to deadpool-sqlite's version requirements [here](https://crates.io/crates/deadpool-sqlite/0.9.0/dependencies).
```
╰─➤  cargo upgrades
miden-node-store
dependency  current  upgrade
rusqlite    0.32.1   0.33.0
```

Update itertools and axum versions

---

.github/workflows/lint.yml
Makefile

Closes #635
Adds a make target for performing workspace lint check in all packages and runs this in PR workflow. See [crate](https://crates.io/crates/cargo-workspace-lints).

ci: add workspace-lints to Makefile and lint.yml

---

.github/actions/build_package/action.yml
.github/workflows/deploy.yml
CHANGELOG.md
bin/faucet/src/config.rs
bin/faucet/src/errors.rs
bin/faucet/src/handlers.rs
bin/faucet/src/main.rs

This PR has a variety of fixes for the faucet and deployment scripts.
Changes actually affecting other operators.
- Faucet webpage was broken because I removed `/*path` which removed serving of `index.css` and `index.js`. I re-added them as constant paths instead. Note that I also tried supporting `/index.html` which is a common entry-point/alias for `/` but this didn't work - the `html` script attempts to fetch `/index.html/index.js`.
- Faucet webpage endpoint is now public: `localhost` -> `0.0.0.0` by default. This is so deployments are automatically public instead of private.
Changes to our deployment workflow scripts.
- Remove `--features testing` vestiges (fix).
- Limit workflow concurrency to 1-per-network.
- Fix naming of deb packages when deploying a branch. The naming scheme used …

feat: deployment related fixes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/faucet/src/static/index.js

We forgot to update the faucet's script file when upgrading account ID from 1 to 2 felts.
I've also added in a changelog entry for the previous version's bugfix.

fix: faucet webpage rejects valid account IDs

---

.github/workflows/package.yml

Packaging release artifacts fails because the `github.ref` returns the full git reference instead of the tag. i.e. it gives `refs/tags/vA.B.C`.
The fix is to use `github.ref_name` 🫤
Thankfully the workflow can be triggered manually where it correctly uses the input version as the tag. This PR just fixes it for the next release trigger; though we'll have to create a fake release to actually test this ahead of time.

ci: fix release tag reference

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/faucet/Cargo.toml
bin/faucet/src/client.rs
bin/faucet/src/config.rs
bin/faucet/src/main.rs
bin/node/Cargo.toml
bin/node/src/config.rs
config/miden-node.toml
crates/block-producer/Cargo.toml
crates/block-producer/src/config.rs
crates/block-producer/src/server.rs
crates/rpc/Cargo.toml
crates/rpc/src/config.rs
crates/rpc/src/server/api.rs
crates/rpc/src/server/mod.rs
crates/store/Cargo.toml
crates/store/src/config.rs
crates/store/src/server/mod.rs
crates/utils/src/config.rs

Closes #651
* Remove Endpoint and Protocol types from util crate
* Use url::Url for handling endpoints both in TOML configuration and runtime

chore: remove Endpoint and Protocol types

---

CHANGELOG.md
Cargo.lock
bin/node/src/main.rs
crates/utils/Cargo.toml
crates/utils/src/logging.rs

This PR adds a `--open-telemetry` flag to the node's `start` command. This exports traces to an open-telemetry backend.
The various settings of this exporter can be controlled by the various environment variables specified by the standard e.g.
```
export OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io"
```
sets the target endpoint.
This is just initial support for this; our actual traces are still _very_ non-conforming to the standard.

feat: open-telemetry exporter

---

CHANGELOG.md
Cargo.lock
crates/block-producer/src/server.rs
crates/block-producer/src/store/mod.rs
crates/rpc/src/server/api.rs
crates/store/src/server/mod.rs
crates/utils/Cargo.toml
crates/utils/src/errors.rs
crates/utils/src/lib.rs
crates/utils/src/tracing/grpc.rs
crates/utils/src/tracing/mod.rs

This PR enables tracing across RPC boundaries using open-telemetry.
Open-telemetry supports smuggling trace ID context across HTTP/RPC calls by embedding this context in various headers. In our case we are using gRPC metadata headers (which in  turn are just binary encoded http headers I believe). Notably, this context includes the sender's trace ID which allows us to connect the dots on the receiver end.
The general idea is that a trace should represent one cohesive item of work. Most examples are of course web-focussed and essentially boil down to a single user request being represented by one trace. In our world this becomes one trace per:
- RPC component request
- Single batch building
- Single block building
- Any other tasks we might have in the future
All of these cross our …

feat: remote tracing context

---

CHANGELOG.md
crates/store/src/db/mod.rs
crates/store/src/db/sql/mod.rs
crates/store/src/state.rs

Ref #664 
Replaces taking a `Vec` in `select_block_headers` with taking an `impl Iterator`

feat: taking iterator in select_block_headers

---

CHANGELOG.md
bin/faucet/src/handlers.rs
bin/faucet/src/main.rs

Closes #671.
Created #673 to create tests for this.
--------------
I've deployed this to devnet and confirmed that 
- both background and favicon load as expected, and
- no console errors
Did require clearing my cache first.

fix(faucet): missing background and favicon routes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/block-producer/Cargo.toml
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/mempool/tests.rs
crates/block-producer/src/store/mod.rs
crates/store/src/server/api.rs
crates/utils/Cargo.toml
crates/utils/src/logging.rs
crates/utils/src/tracing/mod.rs

This PR reworks the instrumentation of the block builder to
1. align it more closely with open-telemetry standards, and
2. improve the telemetry and span information emitted
I also fix remote span context not being sent (propagator was not being set).
I've leant heavily on `#[instrument]` because manually instrumenting sync and async function calls is painful and error prone. The former requires `span.enter()` and `span.exit()`, and the latter requires `async_call.instrument(span).await`. This is easy to forget.
The downside is that code must first be structured by function/stage because `#[instrument]` cannot be applied to code blocks `{ ... }`. Though maybe this is an upside as well. I essentially structured the pipeline based on how I wanted the span information to be tracked.
- …

feat(block-producer): instrument block building

---

Cargo.lock
Cargo.toml
crates/block-producer/src/test_utils/batch.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/test_utils/store.rs
crates/store/src/db/sql/mod.rs
crates/store/src/genesis.rs
crates/store/src/state.rs

We needed the branch to test some features on the client properly.
EDIT: Didn't realize the `next` branch was already using a pinned commit from `miden-base`. Not sure if there is a specific reason for this but we still need a newer version.

chore: Use `miden-base`'s `next`

---

CHANGELOG.md
Cargo.lock
bin/faucet/src/main.rs
bin/node/src/main.rs
crates/test-macro/src/lib.rs
crates/utils/Cargo.toml
crates/utils/src/logging.rs

This PR upgrades the `otel` family of crates from v0.27 to v0.28. The `tracing_opentelemetry` crate is off-by-one.
I've added filtering to the open-telemetry trace exporter. Previously it was exporting everything at a rate of ~150 spans/events per second, which has now dropped to ~3.
I've also refactored the tracing/logging setup to get rid of the redundancy and make setup more obvious.
I'm not adding this to the changelog since no release contains otel exporting yet.
Closes #688 and closes #682

chore: upgrade otel crates and apply filters to exporter

---

crates/store/Cargo.toml
crates/store/src/db/migrations/001-init.sql
crates/store/src/db/mod.rs
crates/store/src/db/sql/mod.rs
crates/store/src/db/tests.rs
crates/store/src/state.rs

Adds `execution_mode` and `consumed` columns to the `notes` table.
Both are written when notes are inserted; however the `consumed` column is currently never set to `true` as we don't have that information available when applying a block (yet).
I've also added a pagination method to iterate over unconsumed network notes. This is intended to initialize the network transaction builder, probably via a streaming gRPC method. The implementation is copied from another note selection query so it should be correct.
Closes #696

feat(store): track network notes

---

.github/workflows/lint.yml

Pin cargo machete to a specific version since the latest one requires Edition 2024 which causes the action to fail (see current next).
Related: https://github.com/0xPolygonMiden/miden-base/pull/1181

Pin cargo machete to a specific version

---

CHANGELOG.md
Cargo.lock
README.md
bin/node/src/config.rs
config/miden-node.toml
crates/block-producer/Cargo.toml
crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/config.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/server.rs

feat: add remote block prover as optional

---

CHANGELOG.md
bin/node/src/config.rs
crates/store/src/config.rs
crates/store/src/db/migrations.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql/utils.rs
crates/store/src/server/api.rs
crates/store/src/server/db_maintenance.rs
crates/store/src/server/mod.rs
crates/store/src/state.rs

Implemented database optimization routine:
1. Full optimization with shrinking and analysis on node start.
2. Limited indexes analysis in background each day (default value, configurable).
This is a recommended way according to docs: https://www.sqlite.org/pragma.html#pragma_optimize
Such optimization routine should help query planner to better make decision which index to use when it has choice.

Implemented database optimization routine

---

crates/store/src/db/mod.rs
crates/store/src/db/settings.rs
crates/store/src/db/sql/mod.rs
crates/store/src/db/sql/utils.rs

Improved `insert_sql!` macro (added support for `OR REPLACE` and `OR IGNORE` conflicts resolution).
This feature was extracted from the https://github.com/0xPolygonMiden/miden-node/pull/563 PR.

feat: improve `insert_sql!` macro

---

Cargo.lock
bin/faucet/src/store.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/test_utils/store.rs
crates/proto/src/generated/requests.rs
crates/proto/src/generated/responses.rs
crates/proto/src/generated/store.rs
crates/rpc-proto/proto/requests.proto
crates/rpc-proto/proto/responses.proto
crates/rpc-proto/proto/store.proto
crates/store/src/db/mod.rs
crates/store/src/db/sql/mod.rs
crates/store/src/server/api.rs
crates/store/src/state.rs
proto/requests.proto
proto/responses.proto
proto/store.proto

This is an auxiliary PR.
Since the query to get the unconsumed notes from the store is paginated, decided that it's best to delegate the pagination also at the endpoint level, instead of streaming the response.

feat: add `get_network_notes` endpoint to the store

---

crates/store/src/db/migrations.rs
crates/store/src/db/pool_manager.rs

For whatever reason the changes in the sqlite pool management introduced in #728 no longer works with manually updating the pragma values. This caused connection creation to fail.
This PR updates it to use a builtin method instead.
This PR _does not_ fix the bad errors messages, those are left for a separate issue.

fix(store): database connections fail due to pragma

---

CHANGELOG.md
bin/faucet/src/main.rs

closes #736 
This PR allows an user to do request like:
```bash
curl -X 'POST' -d '{"asset_amount": 100, "is_private_note": false, "account_id": "0xe1ed79e8ea294d000000e1a0de7be2"}' -H 'Content-Type: application/json' http://0.0.0.0:8080/get_tokens --output output.txt
```

feat: allow content-type header

---

.github/workflows/book.yml

I'm unsure what the difference is to `miden-vm` setup, but the fix here was simply deploying the proper build directory.
I've also added caching because some of the `mdbook` plugins take several minutes to build.
Closes #741.

docs: fix book deployment

---

crates/store/src/db/sql/mod.rs

#728 introduced a [correction](https://github.com/0xPolygonMiden/miden-node/commit/26dbee7d8e5302f3eb8e9b23df3121b78ce163b6#diff-80fe25b196f42f66acaa4e63c5a23552c239be2ea7d0ea6a9050226ab63169a3R47) to `notes` table where a note now has the associated account ID as a foreign key.
Block application however first inserts notes, before inserting new accounts. This PR simply flips the order to the correct one.
Fixes #753.
- Our store error messages are opaque with several `err.to_string()` which hides the actual errors.
- For the error in question, we also have no idea which sql query it is that is failing since we lump them all into the same boat.
- Since the `store` is essentially just a gRPC server, there is nowhere where the errors actually get logged properly. The only error logs are from …

fix: note submission causes database to break

---

bin/node/src/commands/mod.rs

Currently, on `next`, using the default values when starting up is causing an error:
```bash
error: invalid value '5_000' for '--block.interval <MILLISECONDS>': invalid digit found in string
For more information, try '--help'.
```
I was running:
```
miden-node bundled start --rpc.url http://0.0.0.0:57291 --data-directory data
```
Removing the underscore from the default values fixed the issue.

fix: block and batch default intervals

---

Cargo.lock
Cargo.toml
bin/faucet/Cargo.toml
bin/node/Cargo.toml
crates/block-producer/Cargo.toml
crates/proto/Cargo.toml
crates/utils/Cargo.toml

This PR updates `miden-base` dependencies to be pulled from crates.io. Also:
- Updated `http` dependency version from `1.2` to `1.3`.
- Moved `anyhow` dependency declaration to the root `Cargo.toml` file.

Update miden-base dependencies to crates.io versions

---

Cargo.lock
bin/faucet/Cargo.toml
bin/faucet/src/stub_rpc_api.rs
crates/rpc/Cargo.toml
crates/rpc/src/server/mod.rs
crates/utils/Cargo.toml

Addresses #773.
Updates:
- ~`tonic-web` -> v0.13~
- `opentelemetry` -> v0.29
- `opentelemetry-otlp` -> v0.29
- `opentelemetry_sdk` -> v0.29
- `tracing-opentelemetry` -> v0.30
Remains unupdated:
- `tonic`: needs next `opentelemetry` release.
- `tonic-build`: needs `tonic` update.
- `rusqlite`:  needs next `rusqlite_migration` release.

chore: update dependencies

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/stress-test/Cargo.toml
bin/stress-test/src/main.rs
crates/block-producer/Cargo.toml
crates/block-producer/src/block_builder/mod.rs
crates/block-producer/src/domain/transaction.rs
crates/block-producer/src/store/mod.rs
crates/block-producer/src/test_utils/batch.rs
crates/block-producer/src/test_utils/block.rs
crates/block-producer/src/test_utils/store.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql/mod.rs
crates/store/src/db/tests.rs
crates/store/src/genesis.rs
crates/store/src/state.rs

Update usages of account updates and batch and block to use the newly introduced `TransactionHeader` from https://github.com/0xPolygonMiden/miden-base/pull/1247.
These are relatively minor updates. I think the only thing worth calling out is the insertion of the transactions into the DB. Currently the table has these fields:
```sql
CREATE TABLE transactions (
transaction_id BLOB    NOT NULL,
account_id     BLOB    NOT NULL,
block_num      INTEGER NOT NULL,
```
We could insert more data here from the `TransactionHeader`, but how exactly depends on some details I'm not familiar with, like should we insert notes into this table and reference them via a foreign key or is that a bad idea because we remove notes from the notes table when they're consumed?.
If we want to support the explorer to …

Update to use `TransactionHeader`

---

Cargo.lock
bin/faucet/src/client.rs
bin/faucet/src/store.rs
crates/block-producer/src/test_utils/account.rs
crates/store/src/db/tests.rs

As part of the migration to the newest revision of `next`:
- updated the test utils to implement the new `NetworkAccount` parameters
- updated the faucet `DataStore`

refactor: Update faucet data store

---

Cargo.lock
crates/block-producer/Cargo.toml
crates/block-producer/src/mempool/mod.rs
crates/block-producer/src/mempool/tests.rs
crates/utils/Cargo.toml
crates/utils/src/logging.rs

Relates to #725
- Adds support for testing trace content via `miden_node_utils::logging::setup_test_tracing()`.
- Imports the [serial_test](https://crates.io/crates/serial_test) crate for testing purposes.
- Adds tests to block-producer crate's mempool module and fixes instrumentation typo.

Add trace unit tests for block-producer mempool

---

CONTRIBUTING.md
README.md
docs/src/developer/codebase.md
docs/src/developer/index.md
docs/src/index.md
docs/src/operator/index.md
docs/src/operator/installation.md
docs/src/user/rpc.md

This PR updates outdated URLs across all Markdown files to reflect the repository renaming from `0xPolygonMiden` to `0xMiden`.  
It also updates GitHub Pages links from `0xpolygonmiden.github.io` to `0xMiden.github.io`.

docs: update old GitHub and GitHub Pages URLs to new 0xMiden naming

---

CHANGELOG.md
bin/faucet/src/stub_rpc_api.rs
crates/block-producer/src/server.rs
crates/proto/src/generated/block_producer.rs
crates/proto/src/generated/responses.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/store.rs
crates/rpc/src/server/api.rs
crates/store/src/server/api.rs
crates/utils/src/tracing/grpc.rs
proto/proto/block_producer.proto
proto/proto/responses.proto
proto/proto/rpc.proto
proto/proto/store.proto

Closes #794.
This PR adds a new `/status` endpoint on the store, block-producer and RPC components. The RPC endpoint hits the store and block-producer and aggregates their status into a single status response:
```
{
"version": "0.9.0",
"store_status": {
"version": "0.9.0",
"status": "connected",
"chain_tip": 684
},
"block_producer_status": {
"version": "0.9.0",
"status": "connected"
}
}
```
This endpoint can be easily accesed using Postman or grpcurl.
To run using grpcurl: 
```
grpcurl -import-path ./proto/proto -proto rpc.proto -plaintext localhost:57291 rpc.Api.Status
```

feat: add `/status` endpoint

---

.github/actions/build_package/action.yml
Cargo.lock
Cargo.toml
bin/faucet/src/client.rs
bin/node/Dockerfile
bin/stress-test/Cargo.toml
crates/block-producer/Cargo.toml
docs/book.toml

Hey team, I walked through the repo and swapped every `0xPolygonMiden` reference for `0xMiden`
Pure rename—no code or build behavior changed.

chore: migrate repository links from 0xPolygonMiden to 0xMiden

---

CHANGELOG.md
bin/faucet/Cargo.toml
bin/faucet/src/client.rs
bin/faucet/src/handlers.rs
bin/faucet/src/main.rs

Relates to #811.
- Adds `--enable-otel` flag and `MIDEN_FAUCET_ENABLE_OTEL` to faucet.
- Adds instrumentation to functions in the faucet that pertain to RPC endpoints.

Add instrumentation to faucet

---

Cargo.lock

Updates the version of `miden-base` in the node, this is needed to keep compatibility with the client (that is [also being updated](https://github.com/0xMiden/miden-client/pull/907))

fix: run `cargo update`

---

bin/faucet/src/faucet/mod.rs
bin/faucet/src/faucet/updates.rs
bin/faucet/src/main.rs
crates/block-producer/src/domain/transaction.rs
crates/block-producer/src/mempool/inflight_state/mod.rs
crates/store/src/server/api.rs
crates/utils/src/config.rs

Currently, all the PRs are failing in the lint step because of the new rust version. In next is being fixed with https://github.com/0xMiden/miden-node/pull/850 , and looks like it is going to be a more definitive solution, boxing large variants. I created this PR with lint `allow`s so we can unlock the faucet PRs that use main as base.

fix(temporary): enums too large

---

Cargo.lock
bin/faucet/src/client.rs
crates/block-producer/src/server.rs
crates/block-producer/src/test_utils/account.rs
crates/store/src/db/tests.rs
crates/store/src/state.rs

Update needed to fix client's CI. Updates `miden-base`, removing the old `NetworkAccount` enum.

fix: run `cargo update` and fix build

---

Cargo.lock
bin/node/Cargo.toml
bin/node/src/commands/block_producer.rs
bin/node/src/commands/bundled.rs
bin/node/src/commands/mod.rs
bin/node/src/commands/rpc.rs
bin/node/src/commands/store.rs
bin/node/src/main.rs
bin/node/src/system_monitor.rs
crates/store/src/server/mod.rs

Addresses https://github.com/0xMiden/miden-node/issues/686.
This PR introduces a `SystemMonitor` struct as a module of the node binary. This struct runs a loop where it collects system metrics and posts those stats in a tracing event. To collect the system metrics, it uses [sysinfo](https://docs.rs/sysinfo/latest/sysinfo/). The monitor is run in a separate thread; it spawns when running the bundled node, or on the start command of each component independently.
If a block-producer or rpc component is started independently, the store stats will be not be shown.
(open to suggestions on more useful metrics to add)
```
info!(
target: COMPONENT,
// System memory
system_memory_limit,
system_memory_available,
system_memory_usage,
system_memory_utilization,
// System CPU
system_cpu_physical_count, …
```

feat: add system monitor

---

CHANGELOG.md
bin/faucet/Cargo.toml
bin/faucet/src/faucet/mod.rs

Closes #823 
The issue of the duplicated notes ID's had its origin in always using the same serial numbers for notes. That, generally, wasn't a problem because we were usually using different receiver IDs and asset amounts, and that modifies the final `NoteId`, but when repeating those values it was generating the error described in the issue.
The serial number was always the same because we were copying the Rng generator, thus always using the same inner index for the generator and getting the same value.

fix: duplicated note ids

---

CHANGELOG.md
Cargo.lock
bin/faucet/Cargo.toml
bin/faucet/src/config.rs
bin/faucet/src/main.rs
bin/faucet/src/server/get_tokens.rs
bin/faucet/src/server/mod.rs
bin/faucet/src/server/pow.rs
bin/faucet/src/server/resources/index.html
bin/faucet/src/server/resources/index.js

Part of #821 
This PR adds a Proof-of-Work mechanism that ensures that the client spends at least ~2 seconds before being able to mint tokens.
It uses sha3-256 as hashing function and works by:
1. Before requesting token, the client sends a request to `/pow` and gets a random seed, a difficulty and a server signature.
- The seed is a random generated hex string with 64 digits.
- The difficulty is a number that represents the amount of leading zeros that the client needs to look for.
- The current timestamp of the server.
- The server signature is the hash of a secret server salt + the random seed + the timestamp.
2. The client uses the random seed to get a nonce such that the resultant digest has at least `difficulty` leading zeroes.
3. The server, in the `/get_tokens` endpoint, receives …

feat: add PoW to faucet endpoint

---

Cargo.lock
Cargo.toml
bin/faucet/src/client.rs
bin/node/Dockerfile
bin/stress-test/Cargo.toml
crates/block-producer/Cargo.toml

In preparation for the 0.9 release, this PR updates the versions of the miden crates, so that the latest stable released version is used. This is also needed so that we can also update the client's versions.

feat: update miden crate versions

---

crates/rpc/src/server/accept.rs

Seems like `tonic-web-wasm-client` uses a [different accept header](https://github.com/devashishdxt/tonic-web-wasm-client/blob/75762cbc8777d4c493648983e94f014e25e6af6b/src/call.rs#L44-L46) than what the node expects. This meant that all rpc requests failed because the header coulnd't be parsed.
This PR makes it so that the version requirement is ignored if the header doesn't have the expected format.
Note: We also saw some requests with `"*/*"` as the accept header but I couldn't find this in the tonic's code.

fix: ignore unexpected accept headers

---

Cargo.lock
Cargo.toml
bin/faucet/Cargo.toml
bin/faucet/src/faucet/mod.rs
bin/faucet/src/faucet/updates.rs
bin/faucet/src/rpc_client.rs
bin/node/Cargo.toml
bin/stress-test/Cargo.toml
crates/block-producer/Cargo.toml
crates/block-producer/src/domain/transaction.rs
crates/block-producer/src/errors.rs
crates/block-producer/src/mempool/inflight_state/mod.rs
crates/proto/Cargo.toml
crates/rpc/Cargo.toml
crates/store/Cargo.toml
crates/store/src/server/api.rs
crates/test-macro/Cargo.toml
crates/utils/Cargo.toml
crates/utils/src/config.rs

Closes https://github.com/0xMiden/miden-node/issues/855.
This PR removes the clippy allows that were added as a hotfix for the new clippy warnings. 
For addressing them, this PR boxes the `tonic::Status` struct when used in error variants and changes some error handling to account for it.

chore: fix clippy new warnings

---

bin/node/src/commands/bundled.rs
crates/ntx-builder/src/builder/mod.rs
crates/ntx-builder/src/builder/server/state.rs
crates/proto/src/domain/note.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql/mod.rs
crates/store/src/errors.rs
crates/store/src/server/api.rs
crates/store/src/state.rs
proto/proto/responses.proto

After [running a test](https://github.com/0xMiden/miden-client/pull/928/files#diff-593edd05ec1650928be20f1b680c82073de82143707903d4b76d31c4fa8e8e89R529), we found some issues related to the latest refactors in the NTB. This PR fixes them and adds minor refactors. I've also tested the builder by spamming with some notes for accounts that don't exist to see how it'd work and how the traces look.

fix(ntx): Conversions and column rename

---

crates/rpc/src/tests.rs

Fix for oversight in accept header unit test which broke after bumping version from 0.9.0 to 0.10.0.

chore: Fix accept header unit test after 0.10.0 bump

---

bin/faucet/README.md
bin/node/src/commands/store.rs

The default token supply generated on genesis is 1e6. This can run out pretty quickly for the purposes of our testnet faucet, for example.
- Update genesis faucet token decimals to 6 and supply to 1e11 * 1e6.
- Replace POL token symbol with MIDEN.

chore: Bump genesis faucet supply to u32 max

---

Cargo.lock
crates/rpc/Cargo.toml
crates/rpc/src/server/accept.rs
crates/rpc/src/server/mod.rs
docs/src/developer/rpc.md

closes https://github.com/0xMiden/miden-node/issues/788
This PR adds a test to ensure that the RPC server has enabled web support. The test makes a status request and checks that the response contains the CORS headers.
Additionally updated a doc and a test to show the correct version header format.

test: gRPC web support

---

.cargo/config.toml
Cargo.lock
Cargo.toml
Makefile
bin/faucet/Cargo.toml
crates/block-producer/Cargo.toml
crates/ntx-builder/Cargo.toml
crates/rpc/Cargo.toml
crates/store/Cargo.toml

From the client, in order to make the proving service library available from `wasm32` targets, the repo was missing the configuration for `getrandom`. This PR adds it alongside a check that verifies whether the proving service client library can be built for web environments.
Additionally, because the proving service library crate relies on `miden-objects` and `miden-tx`, we need to make sure they dont' come with default features because these include `std` which makes the build fail.

refactor: Valid nostd build for proving service client

---

.github/workflows/build-docker.yml
.github/workflows/publish-docker.yml

Closes #277
Triggered the on-release workflow manually to test: https://github.com/0xMiden/miden-node/actions/runs/15625025989/job/44017494929
Packages successfully published here: https://github.com/orgs/0xMiden/packages?repo_name=miden-node
Uses AWS S3 as cache backend for the Docker layers.

ci: Add cache for Docker workflows

---

.github/workflows/build-docker.yml

PRs created by forks of this repo cannot use secrets until they are approved. This means that the docker build workflow will fail for those PRs because it requires access to the S3 backend for caching.
Verified the non-fork version did use cache here https://github.com/0xMiden/miden-node/pull/979.
- Only use AWS S3 and Docker caching for the PR Docker build workflow when the PR is created from the main repository, not a fork

ci: Cache Docker only on non-forks

---

.github/workflows/publish-debian-all.yml

We forgot to split the Debian publish steps into separate jobs. They are all serially executed because of this.
- Move Debian publish steps into separate jobs for each service

ci: Split debian steps into jobs

---

crates/block-producer/src/test_utils/account.rs

The [new version of Rust](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/) just came out. It includes a new lint rule: [obfuscated if else](https://rust-lang.github.io/rust-clippy/master/index.html#obfuscated_if_else).

fix(clippy): obfuscated if else

---

crates/store/src/db/migrations.rs

Fixes a `TODO`.
Reduces the amount of bytes when hashing but also breaks existing migration hashes. Not sure how to handle code upgrades in this case.

feat: remove comments from SQL commands

---

CHANGELOG.md
crates/block-producer/src/server.rs
crates/ntx-builder/src/builder/mod.rs
crates/rpc/src/server/mod.rs
crates/store/src/server/mod.rs

This adds support for gRPC server reflection `v1alpha` as an addition to the already supported `v1`.
This version is deprecated but not all external applications have migrated. Notably, this includes `postman` which doesn't work our RPC endpoint currently due to this.
The tracking issue for postman is https://github.com/postmanlabs/postman-app-support/issues/13120. Once this is closed and released we can consider reverting this support, though there probably isn't much harm in simply keeping it until its formally removed in `tonic` etc.

feat: support gRPC server reflection v1 alpha

---

Cargo.lock

This should _hopefully_ fix the CI/build issues once everyone is up to this point.
I'm actually curious if the build itself passes with the poisoned gh cache.

chore: bump base

---

Cargo.lock
Cargo.toml
bin/stress-test/Cargo.toml
bin/stress-test/src/seeding/metrics.rs

Address an assumption that doesn't hold for sqlite 3.46.1 as shipped with fedora 41

fix: stress-test assumed a -wal file exist from the get go

---

crates/store/src/db/migrations.rs
crates/store/src/db/mod.rs
crates/store/src/db/sql/mod.rs
crates/store/src/errors.rs
crates/store/src/state.rs

Carve out from #928 
Introduces two intermediate functions `framed` and `framed_without_transaction`, which take a closure each, to either operate on a `&mut Transaction<'_>` or `&mut Connection` respectively. It puts all error handling of the sync/async boundary into those functions rather than have it at each wrapping of a `sql::*` function.
Also uses `NullifierInfo` more, rather than using `(Nullifier, Blocknumber)`, but does NOT expose it to the user in this PR, yet!

store: minor refactor to reduce boilerplate 

---

Cargo.lock
bin/node/src/commands/store.rs
bin/remote-prover/src/api/prover.rs
bin/stress-test/src/seeding/mod.rs
crates/block-producer/src/server.rs
crates/block-producer/src/test_utils/proven_tx.rs
crates/ntx-builder/src/builder/data_store/account_cache.rs
crates/store/src/db/sql/mod.rs
crates/store/src/db/tests.rs

This PR updates the `miden-lib` dependencies and fixes the generated build errors. Mainly the use of `LexicographicWord` in the store. 
The lock file was updated with `cargo update -p miden-lib` so the changes are only related to this base update.

fix: update `miden-lib` and use `LexicographicWord` in store

---

Makefile

We have `cargo-machete` as a CI pass, but it's not part of our `make lint` target. Feel free to close this if it's intentional.

fix: machete as lint

---

docs/src/operator/monitoring.md

Closes #711.
Add comprehensive Honeycomb queries, triggers, and board examples to the monitoring documentation. Includes examples for:
- Block and batch performance monitoring
- Error detection and alerts
- RPC performance tracking
- Advanced troubleshooting with BubbleUp
These examples are based on the actual spans and telemetry data emitted by the node components, helping operators effectively monitor their Miden node deployment.

docs: add Honeycomb monitoring examples

---

Cargo.lock
Cargo.toml
bin/faucet/Cargo.toml
bin/node/Cargo.toml
bin/remote-prover/Cargo.toml
crates/block-producer/Cargo.toml
crates/ntx-builder/Cargo.toml
crates/proto/Cargo.toml
crates/remote-prover-client/Cargo.toml
crates/store/Cargo.toml

related: https://github.com/0xMiden/miden-node/issues/1024
This PR upgrades the version of:
- fantoccini
- tokio
- proptest
Also removes some unecessary features and uses workspace deps where it was not used.

chore: bump dependencies

---

CHANGELOG.md
crates/ntx-builder/src/state/mod.rs
crates/ntx-builder/src/transaction.rs

I forgot to remove network accounts from the in-progress jail once the transaction completes.
I noticed this while debugging the instrumentation.
I've noticed that the ntx spans aren't actually chaining together. This is because we're spawning a task and not passing along the span.
This PR addresses this (I think) - its difficult to be sure because I can't trigger ntx using client integration tests at the moment.
I've added a call to the outer blocking spawn, and the inner spawn so I assume this should work.

fix(ntx): accounts are never unlocked

---

CHANGELOG.md
Cargo.lock
bin/remote-prover/Cargo.toml
bin/remote-prover/src/api/prover.rs
bin/stress-test/src/seeding/mod.rs
crates/rpc/Cargo.toml
crates/rpc/src/server/api.rs
crates/rpc/src/tests.rs
crates/store/src/db/tests.rs
crates/store/src/genesis/config/mod.rs

chore: check matching account delta commitments

---

Cargo.lock
crates/ntx-builder/src/transaction.rs

Migrations:
- `TransactionExecutor` uses generics instead of `dyn Trait`
- miden-base reference: https://github.com/0xMiden/miden-base/pull/1580
- commit: 8fe85f2c82219b16d65df499caf262e2004ccc9b

chore: update miden-base to latest rev `d6dc69b8`

---

crates/store/src/genesis/config/mod.rs

The default max supply is small enough to get burned through via faucet in a few days / weeks despite rate limiting.
Update default max token supply from 100e9 to 100e15.

chore: Update default genesis max token supply

---

Cargo.lock

To match the version in miden-client as of the latest https://github.com/0xMiden/miden-client/commit/f475d89fd8121bebb41d64579efbe5f1db751546
also needed to bump miden-processor, since one of the commits in base replies on the changes in 0.16.4

chore: update `miden-base` version to `871ac9`

---

.release-plz.toml

cherry-picked b70b365 from `next` to `main` so that the release CI job can be automated

fix: release automation config fix (#1079)

---

CHANGELOG.md
crates/store/src/db/models/conv.rs
crates/store/src/db/models/mod.rs
crates/store/src/db/models/queries.rs
crates/store/src/db/models/types.rs
crates/store/src/db/models/utils.rs
crates/store/src/errors.rs

* Avoids excessive usage of tuple and indexing into them, but prefers types and named fields
* first step to wrapper types for all DB stored and retrieved values

refactor: queries minor cleanup

---

CHANGELOG.md
crates/store/src/db/migrations/2025062000000_setup/up.sql
crates/store/src/db/models/mod.rs
crates/store/src/db/models/queries.rs
crates/store/src/db/models/types.rs
crates/store/src/db/schema.rs
crates/store/src/errors.rs

Modifies the table
* externalizes code by code_commitement into a separate table
* expands former details into separate columns
Closes #1083
Open Issues:

store: deduplicate code blobs stored in database

---

Cargo.lock
Cargo.toml
crates/store/Cargo.toml
crates/store/src/genesis/config/mod.rs

See #1164 
This variant uses an `indexmap` to ensure retaining the insertion order. The additional compilation is neglible since we already depend on `indexmap` transitively through i.e. `tower` and `clap` and others.

refactor: `GensisConfig` retain insertion order

---

bin/remote-prover/src/api/prover.rs

Closes #1102.
Sometimes the `test_prove_transaction` fixture will fail locally on line `330`:
```rust
// Check the failure response
assert!(response_1.is_err() || response_2.is_err());
```
- Fix failing test by adding tokio join of relevant tasks.
- Use `MockBuilder` to add note for execution.

fix: Flaky test_prove_transaction

---

Makefile

chore: add --locked to remote prover install target

---

CHANGELOG.md
crates/ntx-builder/src/state/account.rs
crates/ntx-builder/src/state/mod.rs
crates/ntx-builder/src/store.rs
crates/proto/src/domain/note.rs

Closes #1115.
The NTB only supports single target network notes and does not currently check for this when constructing `NetworkNote` from `Note`.
- Update `NetworkNote` to be an enum with single and multi target variants.
- Add `SingleTargetNetworkNote` and `MultiTargetNetworkNote` types.
- Use `SingleTargetNetworkNote` in NTB.

fix: Enforce single target network notes in NTB

---

CHANGELOG.md
crates/proto/src/generated/rpc.rs
crates/rpc/src/server/api.rs
crates/rpc/src/server/mod.rs
proto/proto/rpc.proto

feat: include genesis block's commitment in Status

---

Cargo.lock
Cargo.toml
crates/block-producer/src/test_utils/note.rs
crates/ntx-builder/src/transaction.rs

Updates the node to use the released version of `miden-base`.

chore: update `miden-base` to v0.11

---

README.md
bin/node/Dockerfile
docs/src/operator/installation.md

CI is currently failing in next because the MSRV of the repo is 1.89 but it wasn't updated in the Dockerfile (and used 1.88). Also updated README and installation docs.

chore: update Rust version in Dockerfile and README

---

CHANGELOG.md
crates/proto/src/domain/note.rs
crates/proto/src/generated/note.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/rpc_store.rs
crates/rpc/README.md
crates/rpc/src/server/api.rs
crates/store/README.md
crates/store/src/db/mod.rs
crates/store/src/db/models/queries/notes.rs
crates/store/src/db/tests.rs
crates/store/src/server/rpc_api.rs
crates/store/src/state.rs
crates/utils/src/tracing/grpc.rs
docs/src/user/rpc.md
proto/proto/rpc.proto
proto/proto/store/rpc.proto
proto/proto/types/note.proto

feat: add GetNoteScriptByRoot endpoint

---

.github/workflows/stress-test-check.yml
CHANGELOG.md
bin/stress-test/README.md
bin/stress-test/src/main.rs
bin/stress-test/src/store/mod.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/rpc_store.rs
crates/rpc/README.md
crates/rpc/src/server/api.rs
crates/store/README.md
crates/store/src/db/mod.rs
crates/store/src/db/models/queries/accounts.rs
crates/store/src/db/models/queries/nullifiers.rs
crates/store/src/db/tests.rs
crates/store/src/server/rpc_api.rs
crates/store/src/state.rs
crates/utils/src/limiter.rs
crates/utils/src/tracing/grpc.rs
docs/src/user/rpc.md
proto/proto/rpc.proto
proto/proto/store/rpc.proto

feat: add pagination to CheckNullifiersByPrefix

---

bin/remote-prover/src/commands/worker.rs
crates/block-producer/src/server/mod.rs
crates/rpc/src/server/mod.rs
crates/store/src/server/mod.rs
crates/utils/src/tracing/grpc.rs

chore: improve gRPC spans

---

Cargo.lock
crates/proto/Cargo.toml
crates/proto/build.rs
proto/Cargo.toml
proto/build.rs

Currently we reduce `miette::Error` to `anyhow::Error`. This retains the `miette` context, upgrading output from:
```
Caused by:
process didn't exit successfully: `/media/humpback/projects/miden/miden-node-bernhard-1185-acounts/target/debug/build/miden-node-proto-build-c8b64ef83bec5c7c/build-script-build` (exit status: 1)
--- stdout
cargo::rerun-if-changed=./proto
cargo::rerun-if-env-changed=BUILD_PROTO
--- stderr
[proto/build.rs:25:5] color_eyre::install() = Ok(
(),
)
[proto/build.rs:26:5] run() = Err(
store/rpc.proto:110:19: expected an identifier, but found '{',
)
Error: 
0: expected an identifier, but found '{'
Location:
proto/build.rs:43
```
to:
```
process didn't exit successfully: `/media/humpback/projects/miden/miden-node-bernhard-1185-acounts/target/debug/build/miden-node-proto-bu …
```

`node-proto-build` - better protox errors

---

crates/block-producer/src/batch_builder/mod.rs
crates/block-producer/src/block_builder/mod.rs
crates/store/src/blocks.rs
crates/utils/src/tracing/span_ext.rs

There are additional transaction, batch, and block metrics we could be capturing / observing.
Closes #1118.
- Add transaction ids to batch attributes
- Add batch ids and transaction ids to block attributes
- Instrument save_block() with block number and size

chore: Add tx, block, and batch metrics

---

crates/utils/src/tracing/grpc.rs

Debugging tracing in Honeycomb. The current approach doesn't work so this will simplify it to a (hopefully) working state.

chore: Display uri directly in span field

---

.github/workflows/msrv.yml
rust-toolchain.toml
scripts/check-msrv.sh

This is essentially a port of https://github.com/0xMiden/crypto/pull/547 on this repo. 
Copying the PR description from there.
----
This adds a CI job (locally runnable) that will check the MSRV of a PR is set correctly on a crate-by-crate basis. If the MSRV is set incorrectly, due to e.g. some feature being used, it will compute the correct MSRV for that crate and indicate it in its error. 
The script's error message can be emulated by manually changing the MSRV to an incorrect version (e.g. "1.87") and running it (`./scripts/check-msrv.sh`).
<details><summary> Sample output (click to unfold) </summary>
```
Checking MSRV for workspace members...
Checking miden-crypto in /Users/huitseeker/tmp/crypto/miden-crypto
Current MSRV: 1.87
ERROR: MSRV check failed for miden-crypto
Searching for …
```

ci: add a rust-toolchain.toml, MSRV ci & check script

---

crates/store/src/db/schema.rs

The Diesel schema declared account_storage_map_values primary key as (account_id, block_num, slot, key, is_latest_update), but the authoritative SQL migration defines it as (account_id, block_num, slot, key). Including is_latest_update in the PK is incorrect: it’s a status flag used for toggling latest rows and is not part of the uniqueness constraint. This mismatch could cause Diesel to infer the wrong primary key shape, leading to incorrect query generation and violating the intended update pattern (update latest=false, insert latest=true). Code and tests already rely on the migration’s definition and filter by (account_id, slot, key) with is_latest_update=true. This edit removes is_latest_update from the PK in schema.rs to match the migration and the implemented logic.

fix(store): align account_storage_map_values PK with migration

---

CHANGELOG.md
crates/proto/src/domain/account.rs
crates/proto/src/generated/rpc.rs
crates/proto/src/generated/rpc_store.rs
crates/rpc/src/server/api.rs
crates/store/src/server/rpc_api.rs
crates/store/src/state.rs
proto/proto/rpc.proto
proto/proto/store/rpc.proto

Part 2 of #1185 - reworks the `GetAccountProof` query with a new type.
The changeset focuses on providing account data / vault entries in the response if they are less than 100 (might be too conservative, for both). @SantiagoPittella

feat: optimize `GetAccountProof` for small accounts
