- proto/src/rustfmt.toml
- rpc/src/config.rs
- rpc/src/main.rs
- rpc/src/server/api.rs
- rustfmt.toml
- store/src/config.rs
- store/src/db.rs
- store/src/main.rs
- store/src/server/api.rs
- utils/src/config.rs
As the tile says, this adds the initial config and formats the existing codebase
> rustfmt: add config and format files

- .editorconfig
> config: add .editorconfig

- proto/proto/requests.proto
- proto/proto/responses.proto
- proto/proto/store.proto
- proto/proto/tsmt.proto
- proto/src/conversion.rs
- proto/src/generated/requests.rs
- proto/src/generated/responses.rs
- proto/src/generated/store.rs
- proto/src/generated/tsmt.rs
- store/src/server/api.rs
Implements the get_transaction_inputs endpoint.
> store: get_transaction_inputs endpoint

- proto/src/conversion.rs
- store/src/db/mod.rs
- store/src/genesis.rs
- store/src/state.rs
> Fix genesis block number

- block-producer/src/cli/mod.rs
- block-producer/src/config.rs
- block-producer/src/main.rs
- block-producer/src/server/api.rs
- node/miden-node-example.toml
- node/src/commands.rs
- node/src/config.rs
- node/src/main.rs
- rpc/src/cli/mod.rs
- rpc/src/config.rs
- rpc/src/main.rs
- rpc/src/server/api.rs
- store/src/cli/mod.rs
- store/src/config.rs
- store/src/genesis.rs
- store/src/main.rs
- store/src/server/api.rs
- utils/Cargo.toml
- utils/src/config.rs
- utils/src/lib.rs
> Fix config file and remove defaults

- store/src/db/mod.rs
Closes #130 
Only one connection from the pool was being initialized with the correct module, which caused incoming requests to randomly fail. This PR adds a hook that gets called on pool object creation that inits the connection correctly.
There might also be a better way to do this but skimming through the docs of the deadpool crate I did not find anything.
> Init DB connections with correct modules

- store/src/db/mod.rs
This does:
- enable foreign key checks
- enable WAL mode
> store: added db pragmas

- rpc/src/cli/mod.rs
- rpc/src/main.rs
- store/Cargo.toml
- store/src/cli/mod.rs
- store/src/main.rs
why: I'm adding the control plane and want an easy way to inspect the store.
> store: added cli query commands

- store/src/config.rs
- store/src/state.rs
> docs: add documentation to the store's State

- store/src/db/tests.rs
As per the PR title. I wanted to add a test for the boundary case of a sync request where the client's block_num is the same as the chain tip, I also added a few tests to some of the existing functions that lacked tests, and tried to organized some of the code per function.
> sql: add unit test for queries

- block-producer/src/batch_builder/batch.rs
- block-producer/src/state_view/mod.rs
As per the title, this just adds a link to the issue #186.
> block_producer: link issue about 1 in-flight tx

- block-producer/src/server/mod.rs
- rpc/src/server/mod.rs
- store/src/server/mod.rs
- utils/src/config.rs
otherwise the code would just panic on the `addrs[0]`
> node: add error message on endpoint resolution failure

- store/src/db/sql.rs
- store/src/db/tests.rs
> Get nullifier prefix from the most significant element

- block-producer/Cargo.toml
- block-producer/src/test_utils/proven_tx.rs
- proto/Cargo.toml
- rpc/Cargo.toml
- store/Cargo.toml
- utils/Cargo.toml
> packages: update Cargo.toml deps and metadata

- proto/proto/account.proto
- proto/proto/block_header.proto
- proto/proto/note.proto
- proto/proto/requests.proto
- proto/proto/responses.proto
- proto/src/domain/blocks.rs
- proto/src/domain/notes.rs
- proto/src/generated/account.rs
- proto/src/generated/block_header.rs
- proto/src/generated/note.rs
- proto/src/generated/requests.rs
- proto/src/generated/responses.rs
- store/src/db/sql.rs
- store/src/db/tests.rs
- store/src/state.rs
Changed types of protobuf fields. This resolves #112.
> Changed types of protobuf fields

- store/src/state.rs
Fixes #213
This joins the task handle and logs if an error happened. As per the comment, the state of the system is probably wrong if this happens, and probably the correct behavior is to shutdown the node, this can be done once #91 is implemented.
> store: log apply_block errors

- block-producer/src/batch_builder/tests/mod.rs
- block-producer/src/block_builder/tests.rs
- block-producer/src/state_view/tests/apply_block.rs
- block-producer/src/state_view/tests/mod.rs
- block-producer/src/state_view/tests/verify_tx.rs
- block-producer/src/txqueue/tests/mod.rs
- proto/src/domain/accounts.rs
- proto/src/domain/digest.rs
- store/src/db/mod.rs
- store/src/db/sql.rs
- store/src/db/tests.rs
- store/src/errors.rs
- store/src/server/api.rs
- store/src/state.rs
This PR addresses the comment here: https://github.com/0xPolygonMiden/miden-node/pull/208#pullrequestreview-1874332670
Finally resolves: https://github.com/0xPolygonMiden/miden-node/issues/74
> Used domain types in the store instead of protobuf

- block-producer/src/block_builder/prover/mod.rs
- block-producer/src/errors.rs
Using `'static str` instead of `String`
> Small error refactoring

- Cargo.lock
- node/src/commands/genesis/mod.rs
updates for breaking changes of [#587](https://github.com/0xPolygonMiden/miden-base/pull/587) of miden base
> fix: fix create_basic_fungible_faucet and create_basic_wallet errors

- Cargo.lock
- Cargo.toml
- bin/node/src/commands/genesis/inputs.rs
- crates/block-producer/src/block_builder/prover/mod.rs
- crates/block-producer/src/block_builder/prover/tests.rs
- crates/block-producer/src/test_utils/block.rs
- crates/block-producer/src/test_utils/store.rs
- crates/proto/proto/block_header.proto
- crates/proto/src/domain/blocks.rs
- crates/proto/src/generated/block_header.rs
- crates/store/src/db/tests.rs
- crates/store/src/genesis.rs
Resolves https://github.com/0xPolygonMiden/miden-node/issues/236
> Changed `version` and `timestamp` field types to `u32`

- Cargo.lock
- crates/block-producer/src/block_builder/prover/tests.rs
- crates/block-producer/src/test_utils/proven_tx.rs
- crates/store/src/db/tests.rs
- crates/store/src/state.rs
Follows https://github.com/0xPolygonMiden/miden-base/pull/673
> fix: Output enum definition

- Cargo.lock
- crates/rpc/Cargo.toml
- crates/rpc/src/server/mod.rs
> rpc: enable tonic-web

- bin/node/src/commands/genesis/mod.rs
> chore: replace println with tracing logs

- Cargo.lock
- crates/block-producer/src/block_builder/prover/block_witness.rs
- crates/block-producer/src/block_builder/prover/tests.rs
- crates/block-producer/src/errors.rs
Fixing build after changes on base: https://github.com/0xPolygonMiden/miden-base/pull/814
> fix: Fix build after base changes

- CONTRIBUTING.md
- bin/faucet/src/client.rs
- bin/faucet/src/config.rs
- proto/account.proto
Hello
I found and fixed several spelling issues.
Glad I could help.
Br, Elias.
> Fix spelling issues

- .github/workflows/deb_packager.yml
- README.md
- packaging/postinst
Closes #355
The various 
```
> #[!TIP]
> ...
```
annotations can be viewed by inspecting the whole file and not the diff which imo is a better way of reading this PR :)
> chore: update installation instructions

- Cargo.lock
- crates/store/src/db/tests.rs
- crates/store/src/state.rs
Needed to update after merging of https://github.com/0xPolygonMiden/miden-base/pull/822
> Updated to the latest `next` of `miden-base`

- .github/workflows/amd_deb_packager.yml
- .github/workflows/arm_deb_packager.yml
Changed name of the amd64 packager
Added arm64 packager that will build on the newly added runner, this may need some iterations to iron out as the arm hosted github runners are still in beta.
> Setting up arm builder using the new runner

- .github/workflows/arm_deb_packager.yml
This is temporary for testing out the new arm runner.
> ci: add manual trigger to arm packager

- .github/workflows/arm_deb_packager.yml
Using the correct runs-on with label to the arm runner.
> Adjusting to use proper label for use with managed runner

- .github/workflows/arm_deb_packager.yml
Fixing a typo for faucet copy during package creation.
> ci: typo fix in package

- crates/store/src/db/mod.rs
- crates/store/src/db/sql.rs
- crates/store/src/server/api.rs
Avoid additional queries for chain tip (get it from the state). For additional info see comment: https://github.com/0xPolygonMiden/miden-node/pull/462#discussion_r1738053261
> Get chain tip from the state

- README.md
- crates/proto/src/generated/requests.rs
- crates/rpc-proto/proto/requests.proto
- proto/requests.proto
- scripts/check-changelog.sh
> docs: fix typos

- Cargo.lock
- Cargo.toml
- crates/block-producer/src/test_utils/proven_tx.rs
Follows https://github.com/0xPolygonMiden/miden-base/pull/897
> test: Add expiration number to proven tx builder

- crates/proto/src/generated/requests.rs
- crates/rpc-proto/proto/requests.proto
- crates/store/src/server/api.rs
- proto/requests.proto
Also addresses https://github.com/0xPolygonMiden/miden-node/pull/521/files#r1811540654 which I thought I had fixed, but I had not committed the file.
> fix: Incorrect validation

- Cargo.lock
- crates/store/Cargo.toml
Closes #524 
Also https://github.com/0xPolygonMiden/miden-node/pull/552 can be closed(wrong branch commit)
> update: deadpool-sqlite

- .github/workflows/deploy.yml
updating testnet secret name. (repo secrets updated accordingly and un-used secrets removed)
> ci: update testnet instance secret

- bin/node/Cargo.toml
- crates/store/Cargo.toml
- crates/store/src/db/mod.rs
- crates/store/src/db/query_plan/mod.rs
- crates/store/src/db/sql/mod.rs
- crates/store/src/db/tests.rs
- crates/store/src/db/transaction.rs
In this PR we address review comments for https://github.com/0xPolygonMiden/miden-node/pull/728 PR.
> Address review comments for #728

- .github/workflows/book.yml
Add `/html` to fix deployment of mdbook.
> Fix deployment of mdbook.

- Cargo.lock
- Cargo.toml
- crates/proto/Cargo.toml
- crates/store/Cargo.toml
- proto/Cargo.toml
> chore: update dependencies

- crates/block-producer/src/block_builder/mod.rs
> chore: Add event for proven block transaction count

- .github/workflows/test-beta.yml
Current checkout syntax is incorrect.
> ci: fix beta toolchain workflow

- bin/faucet/src/server/resources/index.html
Updating instructions following https://github.com/0xMiden/miden-client/pull/960/
> chore(faucet): Update client instructions

- bin/faucet/src/config.rs
- bin/faucet/src/main.rs
- bin/faucet/src/server/challenge.rs
- bin/faucet/src/server/get_tokens.rs
- bin/faucet/src/server/mod.rs
- bin/faucet/src/server/pow.rs
- bin/faucet/src/server/resources/index.js
> chore: refactor PoW and Challenge structs

- bin/proving-service/src/proxy/health_check.rs
- bin/proving-service/src/proxy/worker.rs
> chore: refactor workers health check in proxy

- CHANGELOG.md
- bin/proving-service/src/api/prover.rs
- crates/proving-service-client/Cargo.toml
- crates/proving-service-client/src/lib.rs
- crates/proving-service-client/src/proving_service/batch_prover.rs
- crates/proving-service-client/src/proving_service/block_prover.rs
- crates/proving-service-client/src/proving_service/tx_prover.rs
Importing changes from miden-base main:
- https://github.com/0xMiden/miden-base/pull/1447
- https://github.com/0xMiden/miden-base/pull/1448
> feat: Add TLS support for Proving Service Client

- Cargo.lock
- bin/proving-service/Cargo.toml
- bin/proving-service/src/api/prover.rs
- bin/proving-service/src/commands/mod.rs
- bin/proving-service/src/commands/proxy.rs
- bin/proving-service/src/commands/worker.rs
- bin/proving-service/src/lib.rs
- bin/proving-service/src/main.rs
- bin/proving-service/src/proxy/health_check.rs
- bin/proving-service/src/proxy/mod.rs
- bin/proving-service/src/proxy/status.rs
- bin/proving-service/src/proxy/update_workers.rs
- bin/proving-service/src/proxy/worker.rs
- bin/proving-service/src/utils.rs
> chore: use logs and tracing config from node

- bin/node/src/commands/block_producer.rs
- bin/node/src/commands/bundled.rs
- bin/node/src/commands/mod.rs
- bin/node/src/commands/rpc.rs
- bin/node/src/commands/store.rs
> chore: refactor node CLI commands

- .github/workflows/release-plz-dry-run.yml
- .github/workflows/release-plz.yml
- .release-plz.toml
> chore: automate release & dry-run process

- Cargo.lock
- bin/network-monitor/Cargo.toml
- bin/network-monitor/README.md
- bin/network-monitor/assets/index.html
- bin/network-monitor/src/config.rs
- bin/network-monitor/src/faucet.rs
- bin/network-monitor/src/frontend.rs
- bin/network-monitor/src/main.rs
- bin/network-monitor/src/status.rs
Periodically checks the faucet workflow.
> chore: add faucet check in network monitor

- CHANGELOG.md
- bin/stress-test/src/store/mod.rs
- crates/proto/src/generated/rpc_store.rs
- crates/rpc/README.md
- crates/store/README.md
- crates/store/src/db/mod.rs
- crates/store/src/db/models/queries/mod.rs
- crates/store/src/db/models/queries/notes.rs
- crates/store/src/db/tests.rs
- crates/store/src/server/rpc_api.rs
- crates/store/src/state.rs
- docs/src/user/rpc.md
- proto/proto/store/rpc.proto
> chore: add pagination to SyncNotes
